/* eslint-disable react-hooks/refs */
import { useCallback, useEffect, useRef, useState } from 'react';
import { AppState, Animated, PanResponder, Pressable, StyleSheet, Text, View, useWindowDimensions } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import Svg, { ClipPath, Defs, Path, Image as SvgImage, Rect } from 'react-native-svg';
import { haptics } from '../../src/presentation/haptics';
import { useTheme } from '../../src/presentation/theme/ThemeProvider';
import { speciesRepository } from '../../src/data/repositories/speciesRepository';
import { puzzleRepository } from '../../src/data/repositories/puzzleRepository';
import { PUZZLE_SCOPES, type PuzzleDifficulty, type PuzzleScope, type PuzzleRunState } from '../../src/domain/entities/puzzle';
import { thumbnailFor } from '../../src/data/assets/thumbMap';
import type { Species } from '../../src/domain/entities/species';
import { useMobileSync } from '../../src/sync/MobileSyncProvider';
import { puzzlePiecePath } from '../../src/domain/services/puzzleGeometry';
import { useNetwork } from '../../src/presentation/network/NetworkProvider';

type Tile = { id: number; targetX: number; targetY: number; x: number; y: number; placed: boolean; pan: Animated.ValueXY };
const clampGrid = (value: string | undefined): PuzzleDifficulty => value === '4' ? 4 : 3;
export default function PuzzleScreen(): React.JSX.Element {
  const db = useSQLiteContext(); const router = useRouter(); const params = useLocalSearchParams<{ scope?: string; grid?: string }>(); const insets = useSafeAreaInsets(); const { width } = useWindowDimensions(); const { colors, spacing, radius, typography } = useTheme(); const { requestSync } = useMobileSync(); const { isOffline } = useNetwork();
  const grid = clampGrid(params.grid); const rawScope = params.scope; const scope = (typeof rawScope === 'string' && rawScope in PUZZLE_SCOPES ? rawScope : 'animals_all') as PuzzleScope; const board = Math.min(width - 32, 380); const side = board / grid;
  const [species, setSpecies] = useState<Species | null>(null); const [tiles, setTiles] = useState<Tile[]>([]); const [state, setState] = useState<PuzzleRunState>('ready'); const [moves, setMoves] = useState(0); const [elapsed, setElapsed] = useState(0); const startedAt = useRef(0); const pausedAt = useRef(0); const previousCode = useRef<string | null>(null);

  const load = useCallback(async () => { const pool = await speciesRepository.findQuizPool(db, PUZZLE_SCOPES[scope].classes); const choices = pool.filter((item) => item.codigo !== previousCode.current && item.photo); const pick = (choices.length ? choices : pool)[Math.floor(Math.random() * Math.max(choices.length ? choices.length : pool.length, 1))]; if (!pick) return; previousCode.current = pick.codigo; setSpecies(pick); const order = Array.from({ length: grid * grid }, (_, i) => i).sort(() => Math.random() - 0.5); setTiles(order.map((id, index) => ({ id, targetX: (id % grid) * side, targetY: Math.floor(id / grid) * side, x: (index % grid) * side, y: Math.floor(index / grid) * side, placed: false, pan: new Animated.ValueXY() }))); setState('ready'); setMoves(0); setElapsed(0); }, [db, grid, scope, side]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const sub = AppState.addEventListener('change', (next) => { if (next !== 'active' && state === 'running') { pausedAt.current = Date.now(); setState('paused'); } else if (next === 'active' && state === 'paused') { startedAt.current += Date.now() - pausedAt.current; setState('running'); } }); return () => sub.remove(); }, [state]);
  useEffect(() => { if (state !== 'running') return; const timer = setInterval(() => setElapsed(Date.now() - startedAt.current), 250); return () => clearInterval(timer); }, [state]);
  const complete = useCallback(async (nextTiles: Tile[]) => { if (!nextTiles.every((tile) => tile.placed)) return; setState('completed'); const record = { scope, gridSize: grid, bestTimeMs: elapsed || (Date.now() - startedAt.current), fewestMoves: moves, playedAt: Date.now(), updatedAt: Date.now() }; await puzzleRepository.submit(db, record); void requestSync(); haptics.success(); }, [db, elapsed, grid, moves, requestSync, scope]);
  const createResponder = (tile: Tile) => PanResponder.create({ onStartShouldSetPanResponder: () => !tile.placed, onPanResponderGrant: () => { if (state === 'ready' || state === 'paused') { startedAt.current = Date.now(); setState('running'); } tile.pan.setValue({ x: 0, y: 0 }); }, onPanResponderMove: Animated.event([null, { dx: tile.pan.x, dy: tile.pan.y }], { useNativeDriver: false }), onPanResponderRelease: (_, gesture) => { const nx = tile.x + gesture.dx; const ny = tile.y + gesture.dy; const close = Math.abs(nx - tile.targetX) <= side * 0.18 && Math.abs(ny - tile.targetY) <= side * 0.18; const updated = tiles.map((item) => item.id === tile.id ? { ...item, x: close ? item.targetX : item.x, y: close ? item.targetY : item.y, placed: close || item.placed } : item); setTiles(updated); tile.pan.setValue({ x: 0, y: 0 }); if (Math.abs(gesture.dx) + Math.abs(gesture.dy) > 2) setMoves((count) => count + 1); if (close) haptics.success(); void complete(updated); } });
  const imageSource = species ? (isOffline === true ? thumbnailFor(species.codigo) : species.photo?.url ? { uri: species.photo.url } : thumbnailFor(species.codigo)) : null;
  const renderTile = (tile: Tile) => { const x = tile.id % grid; const y = Math.floor(tile.id / grid); const clipId = `piece-${tile.id}`; return <Animated.View key={tile.id} {...createResponder(tile).panHandlers} style={[styles.tile, { width: side, height: side, left: tile.x, top: tile.y, opacity: tile.placed ? 0.92 : 1 }, { transform: [{ translateX: tile.pan.x }, { translateY: tile.pan.y }] }]}><Svg width={side} height={side}><Defs><ClipPath id={clipId}><Path d={puzzlePiecePath(tile.id, grid, side)} /></ClipPath></Defs>{imageSource ? <SvgImage href={imageSource as never} x={-x * side} y={-y * side} width={board} height={board} preserveAspectRatio="xMidYMid slice" clipPath={`url(#${clipId})`} /> : <Rect width={side} height={side} fill={colors.surfaceVariant} />}</Svg></Animated.View>; };
  return <View style={[styles.screen, { backgroundColor: colors.background, paddingTop: insets.top + spacing.sm }]}><View style={styles.header}><Pressable onPress={() => router.back()} style={[styles.back, { backgroundColor: colors.surface, borderRadius: radius.pill }]}><Text style={{ color: colors.text, fontSize: 24 }}>‹</Text></Pressable><View style={styles.flex}><Text style={[typography.headerTitle, { color: colors.text }]}>Puzzle {grid} × {grid}</Text><Text style={[typography.caption, { color: colors.textMuted }]}>{PUZZLE_SCOPES[scope].label} · {Math.floor(elapsed / 1000)} s · {moves} movimientos</Text></View></View><View style={[styles.board, { width: board, height: board, borderRadius: radius.lg, backgroundColor: colors.surfaceVariant }]}>{tiles.map(renderTile)}</View>{state === 'completed' && species ? <View style={[styles.complete, { backgroundColor: colors.surface, borderRadius: radius.lg }]}><Text style={[typography.cardTitle, { color: colors.text }]}>{species.displayName}</Text><Text style={[typography.body, { color: colors.textSecondary }]}>{species.scientificName}</Text><Text style={[typography.caption, { color: colors.textMuted }]}>Completaste en {Math.round(elapsed / 1000)} s · {moves} movimientos</Text><View style={styles.actions}><Pressable onPress={() => void load()} style={[styles.action, { backgroundColor: colors.play, borderRadius: radius.pill }]}><Text style={{ color: colors.onPlay, fontWeight: '700' }}>Otro puzzle</Text></Pressable><Pressable onPress={() => router.push(`/species/${species.codigo}`)}><Text style={{ color: colors.play, fontWeight: '700' }}>Ver especie</Text></Pressable></View></View> : <Text style={[typography.body, { color: colors.textMuted, textAlign: 'center', marginTop: spacing.lg, paddingHorizontal: 24 }]}>Arrastrá cada pieza hasta su lugar. Si queda cerca de la posición correcta, se encastra automáticamente; si no, vuelve a su posición anterior.</Text>}</View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, alignItems: 'center' }, header: { width: '100%', flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 16 }, back: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center' }, flex: { flex: 1 }, board: { marginTop: 28, overflow: 'hidden', position: 'relative' }, tile: { position: 'absolute', overflow: 'hidden', borderWidth: 0.5, borderColor: 'rgba(41,74,58,0.2)' }, complete: { width: '90%', padding: 20, marginTop: 24, gap: 6 }, actions: { flexDirection: 'row', alignItems: 'center', gap: 20, marginTop: 12 }, action: { paddingHorizontal: 16, paddingVertical: 12 } });
