import { Check, Edit3, Plus, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Notice, PageHeader } from '../components/Ui';
import type { SpeciesSummary } from '../domain';
import { listApprovedImages, listCatalogSources, listContentChanges, listEnrichmentCandidates, listSpecies, listTaxonContent, reviewContentChange, submitContentChange, triageEnrichmentCandidate, type ApprovedImageRow, type CatalogSource, type ContentChangeRow, type EnrichmentCandidateRow, type TaxonContentRow } from '../lib/api';

type Kind='abundance'|'game_profile'|'fact'|'trivia'|'taxon_content';
const LABELS:Record<string,string>={abundance:'Abundancia experta',game_profile:'Dificultad de especie',game_rule:'Regla de juego',fact:'Dato curioso',trivia:'Pregunta de trivia',taxon_content:'Descripción taxonómica'};

export function CatalogContentPage():React.JSX.Element{
  const [species,setSpecies]=useState<SpeciesSummary[]>([]); const [sources,setSources]=useState<CatalogSource[]>([]); const [queue,setQueue]=useState<ContentChangeRow[]>([]); const [candidates,setCandidates]=useState<EnrichmentCandidateRow[]>([]); const [taxa,setTaxa]=useState<TaxonContentRow[]>([]); const [images,setImages]=useState<ApprovedImageRow[]>([]);
  const [speciesId,setSpeciesId]=useState(''); const [kind,setKind]=useState<Kind>('abundance'); const [sourceId,setSourceId]=useState(''); const [body,setBody]=useState(''); const [level,setLevel]=useState('easy'); const [abundance,setAbundance]=useState('common'); const [options,setOptions]=useState(['','','','']); const [correct,setCorrect]=useState(0); const [comment,setComment]=useState(''); const [message,setMessage]=useState(''); const [imageMediaId,setImageMediaId]=useState('');
  const [taxonId,setTaxonId]=useState<string|null>(null); const [taxonRank,setTaxonRank]=useState<'phylum'|'class'|'order'|'family'>('order'); const [taxonClass,setTaxonClass]=useState('Aves'); const [taxonName,setTaxonName]=useState(''); const [taxonSimpleName,setTaxonSimpleName]=useState('');
  const load=()=>Promise.all([listSpecies({pageSize:1000}),listCatalogSources(),listContentChanges(),listEnrichmentCandidates(),listTaxonContent()]).then(([result,sourceRows,changes,candidateRows,taxonRows])=>{setSpecies(result.rows);setSources(sourceRows);setQueue(changes);setCandidates(candidateRows);setTaxa(taxonRows);if(!speciesId&&result.rows[0])setSpeciesId(result.rows[0].id);if(!sourceId&&sourceRows[0])setSourceId(sourceRows.find((row)=>row.code==='natura_uy_editorial')?.id??sourceRows[0].id);});
  useEffect(()=>{void load().catch((error:Error)=>setMessage(error.message));},[]);
  useEffect(()=>{if(kind!=='trivia'){setImages([]);return;}void listApprovedImages(speciesId||undefined).then(setImages).catch(()=>setImages([]));},[kind,speciesId]);
  const selected=useMemo(()=>species.find((item)=>item.id===speciesId),[species,speciesId]);
  const resetTaxon=()=>{setTaxonId(null);setTaxonRank('order');setTaxonClass('Aves');setTaxonName('');setTaxonSimpleName('');setBody('');};
  const editTaxon=(item:TaxonContentRow)=>{setKind('taxon_content');setTaxonId(item.id);setTaxonRank(item.taxonRank);setTaxonClass(item.className);setTaxonName(item.taxonName);setTaxonSimpleName(item.simpleName??'');setBody(item.description);setSourceId(item.sourceId);window.scrollTo({top:0,behavior:'smooth'});};
  const propose=async()=>{setMessage('');try{let values:Record<string,unknown>;let targetSpecies:string|null=speciesId||null;if(kind==='abundance')values={category:abundance,label:{abundant:'Abundante',common:'Común',uncommon:'Poco común',rare:'Rara',very_rare:'Muy rara',unknown:'Sin evaluar'}[abundance],geographic_scope:'Uruguay',source_id:sourceId};else if(kind==='game_profile')values={knowledge_level:level,rationale:body,source_basis:'editorial'};else if(kind==='fact')values={body,source_id:sourceId,sort_order:0};else if(kind==='taxon_content'){targetSpecies=null;values={taxon_rank:taxonRank,kingdom:'Animalia',phylum:'Chordata',class_name:taxonRank==='phylum'?'':taxonClass,taxon_name:taxonName,simple_name:taxonSimpleName||null,language:'es-UY',description:body,source_id:sourceId};}else values={prompt:body,explanation:comment,source_id:sourceId,image_media_id:imageMediaId||null,options:options.map((option,index)=>({body:option,is_correct:index===correct,sort_order:index}))};await submitContentChange({contentType:kind,entityId:kind==='taxon_content'?taxonId:null,speciesId:targetSpecies,values,comment:kind==='trivia'?'':comment});setBody('');setOptions(['','','','']);setComment('');setImageMediaId('');if(kind==='taxon_content')resetTaxon();setMessage('Solicitud enviada para revisión.');await load();}catch(error){setMessage(error instanceof Error?error.message:'No se pudo enviar.');}};
  const review=async(id:string,approve:boolean)=>{try{await reviewContentChange(id,approve,true);await load();}catch(error){setMessage(error instanceof Error?error.message:'No se pudo revisar.');}}; const triage=async(id:string,accept:boolean)=>{try{await triageEnrichmentCandidate(id,accept);setMessage(accept?'Candidato enviado a Revisiones.':'Candidato descartado.');await load();}catch(error){setMessage(error instanceof Error?error.message:'No se pudo procesar el candidato.');}};
  const invalid=kind==='taxon_content'?((taxonRank!=='phylum'&&!taxonClass.trim())||!taxonName.trim()||body.trim().length<30||!sourceId):(!selected&&kind!=='trivia')||(kind!=='game_profile'&&!sourceId)||((kind==='fact'||kind==='trivia')&&!body.trim())||(kind==='trivia'&&options.some((option)=>!option.trim()));
  return <><PageHeader eyebrow="CATÁLOGO ENRIQUECIDO" title="Contenido y juegos" subtitle="Abundancia, taxonomía, dificultad, curiosidades y trivia con fuente y aprobación humana."/>{message&&<Notice kind={message.startsWith('Solicitud')?'success':'error'}>{message}</Notice>}
    <section className="panel editor-panel"><div className="form-grid two"><label className="field"><span>Tipo</span><select value={kind} onChange={(event)=>setKind(event.target.value as Kind)}><option value="abundance">Abundancia experta</option><option value="game_profile">Dificultad de especie</option><option value="fact">Dato curioso</option><option value="trivia">Pregunta de trivia</option><option value="taxon_content">Contenido taxonómico</option></select></label>{kind!=='taxon_content'&&<label className="field"><span>Especie</span><select value={speciesId} onChange={(event)=>{setSpeciesId(event.target.value);setImageMediaId('');}}><option value="">General / sin especie</option>{species.map((item)=><option value={item.id} key={item.id}>{item.payload.commonNames[0]} · {item.payload.scientificName}</option>)}</select></label>}</div>
      {kind==='taxon_content'&&<><div className="form-grid three"><label className="field"><span>Rango</span><select value={taxonRank} onChange={(event)=>setTaxonRank(event.target.value as 'phylum'|'class'|'order'|'family')}><option value="phylum">Filo</option><option value="class">Clase</option><option value="order">Orden</option><option value="family">Familia</option></select></label><label className="field"><span>Clase {taxonRank==='phylum'?'(no corresponde)':''}</span><input disabled={taxonRank==='phylum'} value={taxonClass} onChange={(event)=>setTaxonClass(event.target.value)} placeholder="Aves, Mammalia…"/></label><label className="field"><span>Nombre científico del taxón</span><input className="italic" value={taxonName} onChange={(event)=>setTaxonName(event.target.value)} placeholder="Passeriformes"/></label></div><div className="form-grid two"><label className="field"><span>Nombre simple opcional</span><input value={taxonSimpleName} onChange={(event)=>setTaxonSimpleName(event.target.value)} placeholder="Roedores"/></label></div><label className="field full"><span>Descripción (30–800 caracteres)</span><textarea value={body} onChange={(event)=>setBody(event.target.value)} rows={5}/></label></>}
      {kind==='abundance'&&<label className="field"><span>Categoría</span><select value={abundance} onChange={(event)=>setAbundance(event.target.value)}>{[['abundant','Abundante'],['common','Común'],['uncommon','Poco común'],['rare','Rara'],['very_rare','Muy rara'],['unknown','Sin evaluar']].map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label>}
      {kind==='game_profile'&&<div className="form-grid two"><label className="field"><span>Nivel mínimo</span><select value={level} onChange={(event)=>setLevel(event.target.value)}><option value="easy">Fácil</option><option value="medium">Medio</option><option value="hard">Difícil</option></select></label><label className="field"><span>Justificación</span><input value={body} onChange={(event)=>setBody(event.target.value)}/></label></div>}
      {(kind==='fact'||kind==='trivia')&&<label className="field full"><span>{kind==='fact'?'Texto del dato curioso':'Pregunta'}</span><textarea value={body} onChange={(event)=>setBody(event.target.value)} rows={3}/></label>}
      {kind==='trivia'&&<><div className="form-grid two">{options.map((option,index)=><label className="field" key={index}><span>Opción {index+1} {correct===index?'(correcta)':''}</span><input value={option} onChange={(event)=>setOptions(options.map((value,item)=>item===index?event.target.value:value))}/><button type="button" className="secondary" onClick={()=>setCorrect(index)}>Marcar correcta</button></label>)}</div><label className="field full"><span>Imagen ilustrativa opcional</span><select value={imageMediaId} onChange={(event)=>setImageMediaId(event.target.value)}><option value="">Sin imagen</option>{images.map((image)=><option key={image.id} value={image.id}>{image.label}</option>)}</select><small>Sólo aparecen imágenes aprobadas y compatibles con la especie elegida.</small></label></>}
      {(kind==='abundance'||kind==='fact'||kind==='trivia'||kind==='taxon_content')&&<label className="field"><span>Fuente</span><select value={sourceId} onChange={(event)=>setSourceId(event.target.value)}>{sources.map((source)=><option value={source.id} key={source.id}>{source.name} · {source.license} · {source.usePolicy}</option>)}</select></label>}{kind!=='trivia'&&<label className="field full"><span>Motivo / metodología</span><input value={comment} onChange={(event)=>setComment(event.target.value)}/></label>}
      <div className="header-actions"><button className="primary" disabled={invalid} onClick={()=>void propose()}><Plus size={17}/>{taxonId?'Enviar edición':'Enviar para revisión'}</button>{kind==='taxon_content'&&taxonId&&<button className="secondary" onClick={resetTaxon}>Cancelar edición</button>}</div></section>
    <section className="panel"><h2>Descripciones taxonómicas publicadas</h2><p>La estructura admite filo, clase, orden y familia; cada edición genera una revisión.</p><div className="timeline">{taxa.map((item)=><article key={item.id}><div><header><strong>{({phylum:'Filo',class:'Clase',order:'Orden',family:'Familia'} as const)[item.taxonRank]} · <i>{item.taxonName}</i>{item.simpleName?` — ${item.simpleName}`:''}{item.className?` · ${item.className}`:''}</strong></header><p>{item.description}</p><button className="secondary" onClick={()=>editTaxon(item)}><Edit3 size={15}/>Editar</button></div></article>)}</div></section>
    <section className="panel"><h2>Revisión pendiente</h2>{queue.length===0?<p>No hay contenido pendiente.</p>:<div className="timeline">{queue.map((item)=><article key={item.id}><div><header><strong>{LABELS[item.contentType]??item.contentType} · {item.speciesName??'General'}</strong></header><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(item.proposedValues,null,2)}</pre><small>Propuesto por {item.proposedByName} · {new Date(item.createdAt).toLocaleString('es-UY')}</small><div className="header-actions"><button className="primary" onClick={()=>void review(item.id,true)}><Check size={16}/>Aprobar</button><button className="secondary" onClick={()=>void review(item.id,false)}><X size={16}/>Rechazar</button></div></div></article>)}</div>}</section>
    <section className="panel"><h2>Candidatos automáticos</h2><p>Aceptar sólo los promueve a la bandeja de revisiones de especies; no modifica el catálogo publicado.</p>{candidates.length===0?<p>No hay candidatos importados pendientes.</p>:<div className="timeline">{candidates.map((item)=><article key={item.id}><div><header><strong>{item.scientificName} · {item.fieldPath}</strong></header><p>{String(item.currentValue??'∅')} → {String(item.proposedValue??'∅')} · {item.sourceCode} · confianza {item.confidence==null?'—':Math.round(item.confidence*100)+'%'}</p><small>{item.rationale}</small><div className="header-actions"><button className="primary" onClick={()=>void triage(item.id,true)}><Check size={16}/>Promover a revisión</button><button className="secondary" onClick={()=>void triage(item.id,false)}><X size={16}/>Descartar</button></div></div></article>)}</div>}</section>
  </>;
}
