import { BookOpenCheck, ChevronRight, CircleAlert, Database, Image, Leaf, Plus, Search, ShieldCheck, Volume2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useAuth } from '../auth/AuthProvider';

import { Empty, Loading, PageHeader } from '../components/Ui';
import type { DashboardStats, SpeciesSummary } from '../domain';
import { getDashboardStats, listSpecies, requestPublish } from '../lib/api';
import { navigate } from '../lib/router';

export function DashboardPage(): React.JSX.Element {
  const { profile } = useAuth();
  const [stats, setStats] = useState<DashboardStats | null>(null); const [species, setSpecies] = useState<SpeciesSummary[]>([]); const [error, setError] = useState(''); const [publishing, setPublishing] = useState(false);
  useEffect(() => { void Promise.all([getDashboardStats(), listSpecies({ pageSize: 4, sort: 'recent' })]).then(([nextStats, result]) => { setStats(nextStats); setSpecies(result.rows); }).catch((reason: Error) => setError(reason.message)); }, []);
  if (error) return <Empty title="No pudimos cargar el panel" detail={error} />; if (!stats) return <Loading label="Preparando el catálogo…" />;
  async function publish() { setPublishing(true); try { await requestPublish(); setStats({ ...stats!, dirtyChanges: 0 }); } finally { setPublishing(false); } }
  return <><PageHeader eyebrow="CATÁLOGO EDITORIAL" title="Buen día" subtitle="Esto es lo que necesita atención hoy." action={<button className="primary" onClick={() => navigate('/species/new')}><Plus size={18} /> Nueva especie</button>} />
    <section className="stats" aria-label="Estado del catálogo">
      <article><span className="stat-icon green"><Database /></span><div><small>Especies activas</small><strong>{stats.activeSpecies.toLocaleString('es-UY')}</strong><p>{stats.retiredSpecies} retiradas</p></div></article>
      <article><span className="stat-icon gold"><CircleAlert /></span><div><small>Necesitan revisión</small><strong>{stats.unreviewedSpecies.toLocaleString('es-UY')}</strong><p>Edición pendiente</p></div></article>
      <article><span className="stat-icon sage"><Image /></span><div><small>Con imagen</small><strong>{stats.withImage.toLocaleString('es-UY')}</strong><p>{Math.round(stats.withImage / stats.activeSpecies * 100)}% del catálogo</p></div></article>
      <article><span className="stat-icon blue"><Volume2 /></span><div><small>Con audio</small><strong>{stats.withAudio.toLocaleString('es-UY')}</strong><p>{stats.pendingMedia} medios procesándose</p></div></article>
    </section>
    <section className="work-grid"><article className="panel species-panel"><div className="panel-head"><div><p className="eyebrow">TRABAJO EDITORIAL</p><h2>Especies recientes</h2></div><button className="link-button" onClick={() => navigate('/species')}>Ver todas <ChevronRight size={17} /></button></div><label className="search"><Search size={19} /><input aria-label="Buscar especies" placeholder="Buscar por nombre, familia o código…" onKeyDown={(event) => { if (event.key === 'Enter') navigate(`/species?q=${encodeURIComponent(event.currentTarget.value)}`); }} /></label><div className="species-list">{species.map((item) => <button className="species-row" key={item.id} onClick={() => navigate(`/species/${item.id}`)}><span className={item.imageUrl ? 'species-thumb ready' : 'species-thumb'}>{item.imageUrl ? <img src={item.imageUrl} alt="" /> : <Leaf size={18} />}</span><span className="species-name"><strong>{item.payload.commonNames[0] ?? item.payload.scientificName}</strong><em>{item.payload.scientificName}</em></span><span className="taxon">{item.payload.taxonomy.class} · {item.payload.taxonomy.family}</span><span className={`status ${item.validationState}`}>{item.validationState === 'validated' ? 'Validada' : item.validationState === 'needs_review' ? 'Revisar' : 'Sin revisar'}</span><ChevronRight size={17} /></button>)}</div></article>
      <aside className="right-column"><article className="panel publish-card"><div className="publish-icon"><BookOpenCheck size={24} /></div><p className="eyebrow">CATÁLOGO MÓVIL</p><h2>{stats.dirtyChanges ? `Hay ${stats.dirtyChanges} cambios aprobados sin publicar` : 'El catálogo está al día'}</h2><p>{stats.dirtyChanges ? 'Un administrador puede iniciar la publicación manual cuando corresponda.' : `Última versión publicada: ${stats.lastRelease ?? '—'}.`}</p>{profile?.role === 'admin' && <button className="primary wide" disabled={!stats.dirtyChanges || publishing} onClick={() => void publish()}>{publishing ? 'Solicitando…' : 'Publicar ahora'}</button>}</article><article className="panel activity-card"><div className="panel-head"><div><p className="eyebrow">CONTROL DE CALIDAD</p><h2>Estado general</h2></div><ShieldCheck /></div><ul><li><span className="activity-dot"></span><p><b>Identificadores estables</b><small>Sin duplicados detectados</small></p></li><li><span className="activity-dot"></span><p><b>Base móvil íntegra</b><small>Última verificación correcta</small></p></li><li><span className="activity-dot"></span><p><b>Medios públicos</b><small>Supabase Storage con rutas inmutables</small></p></li></ul></article></aside></section></>;
}
