import { CheckCircle2, CircleAlert, Download, ExternalLink, Rocket } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Empty, Loading, Notice, PageHeader } from '../components/Ui';
import type { CatalogRelease, DashboardStats } from '../domain';
import { getDashboardStats, listReleases, requestPublish } from '../lib/api';

export function ReleasesPage(): React.JSX.Element {
  const [releases, setReleases] = useState<CatalogRelease[] | null>(null); const [stats, setStats] = useState<DashboardStats | null>(null); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const load = () => void Promise.all([listReleases(), getDashboardStats()]).then(([items, nextStats]) => { setReleases(items); setStats(nextStats); }).catch((error: Error) => setMessage(error.message)); useEffect(load, []);
  async function publish() { setBusy(true); try { await requestPublish(); setMessage('La publicación quedó solicitada. Podés seguir trabajando mientras se construye.'); load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo solicitar.'); } finally { setBusy(false); } }
  return <><PageHeader eyebrow="CATÁLOGO MÓVIL" title="Publicaciones" subtitle="Cada versión es verificable y puede descargarse sin actualizar la aplicación." action={<button className="primary" disabled={!stats?.dirtyChanges || busy} onClick={() => void publish()}><Rocket size={18} />{busy ? 'Solicitando…' : 'Publicar ahora'}</button>} />{message && <Notice kind={message.startsWith('La publicación') ? 'success' : 'error'}>{message}</Notice>}
    {stats && <section className="release-summary"><article className={stats.dirtyChanges ? 'dirty' : ''}>{stats.dirtyChanges ? <CircleAlert /> : <CheckCircle2 />}<div><small>Estado editorial</small><strong>{stats.dirtyChanges ? `${stats.dirtyChanges} cambios pendientes` : 'Sin cambios pendientes'}</strong><p>El proceso automático consulta cada 15 minutos.</p></div></article><article><CheckCircle2 /><div><small>Última versión</small><strong>v. {stats.lastRelease ?? '—'}</strong><p>{stats.lastPublishedAt ? new Date(stats.lastPublishedAt).toLocaleString('es-UY') : 'Todavía no publicada'}</p></div></article></section>}
    {!releases ? <Loading /> : releases.length === 0 ? <Empty title="Sin publicaciones" detail="La primera versión aparecerá cuando el catálogo supere la validación técnica." /> : <section className="panel release-list"><div className="table-row table-head"><span>Versión</span><span>Solicitud</span><span>Contenido</span><span>Estado</span><span></span></div>{releases.map((item) => <div className="table-row" key={item.id}><span><strong>Catálogo v. {item.dataVersion}</strong><small>{item.publishedAt ? new Date(item.publishedAt).toLocaleString('es-UY') : 'Aún no publicada'}</small></span><span><b>{item.requestedBy}</b><small>{new Date(item.requestedAt).toLocaleString('es-UY')}</small></span><span><b>{item.speciesCount?.toLocaleString('es-UY') ?? '—'} especies</b><small>{item.databaseSize ? `${(item.databaseSize / 1024 / 1024).toFixed(2)} MB` : 'Construyendo archivos'}</small></span><span className={`job-state ${item.status}`}>{item.status === 'published' ? 'Publicada' : item.status === 'building' ? 'Construyendo' : item.status === 'failed' ? 'Falló' : 'Pendiente'}</span><span className="row-actions">{item.qualityReportUrl && <a className="icon-button" href={item.qualityReportUrl} title="Informe de calidad"><ExternalLink /></a>} {item.status === 'published' && <button className="icon-button" title="Descargar"><Download /></button>}</span></div>)}</section>}
  </>;
}
