import { ArchiveRestore, ArrowLeft, Check, Clock3, History, Plus, Save, ShieldCheck, Trash2 } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';

import { Empty, Loading, Modal, Notice, PageHeader } from '../components/Ui';
import { emptySpeciesPayload, type Revision, type SpeciesPayload, type SpeciesSummary } from '../domain';
import { getSpecies, rollbackRevision, saveSpecies, speciesAction } from '../lib/api';
import { navigate } from '../lib/router';

type Tab = 'identity' | 'taxonomy' | 'presence' | 'biology' | 'conservation' | 'sources' | 'history';
const tabs: Array<[Tab, string]> = [['identity', 'Identidad'], ['taxonomy', 'Taxonomía'], ['presence', 'Presencia'], ['biology', 'Biología'], ['conservation', 'Conservación'], ['sources', 'Fuentes'], ['history', 'Historial']];

export function SpeciesEditorPage({ id }: { id: string | null }): React.JSX.Element {
  const creating = id === null; const [species, setSpecies] = useState<SpeciesSummary | null>(null); const [payload, setPayload] = useState<SpeciesPayload>(emptySpeciesPayload()); const [catalogCode, setCatalogCode] = useState(''); const [revisions, setRevisions] = useState<Revision[]>([]); const [tab, setTab] = useState<Tab>('identity'); const [loading, setLoading] = useState(!creating); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [confirm, setConfirm] = useState<'retire' | 'restore' | null>(null); const [reason, setReason] = useState('');
  useEffect(() => { if (!id) return; void getSpecies(id).then((result) => { setSpecies(result.species); setPayload(result.species.payload); setCatalogCode(result.species.catalogCode); setRevisions(result.revisions); setLoading(false); }).catch((error: Error) => { setMessage(error.message); setLoading(false); }); }, [id]);
  const title = payload.commonNames[0] || payload.scientificName || 'Nueva especie'; const dirty = useMemo(() => creating || JSON.stringify(payload) !== JSON.stringify(species?.payload) || catalogCode !== species?.catalogCode, [payload, species, catalogCode, creating]);
  const patch = <K extends keyof SpeciesPayload>(key: K, value: SpeciesPayload[K]) => setPayload((current) => ({ ...current, [key]: value }));
  async function save() { if (!payload.scientificName.trim() || !catalogCode.trim()) { setMessage('El nombre científico y el código Natura UY son obligatorios.'); return; } setSaving(true); setMessage(''); try { const savedId = await saveSpecies({ id: species?.id, catalogCode, payload, expectedRevision: species?.revision ?? 0, reason: reason || (creating ? 'Alta de especie' : 'Rectificación editorial') }); if (creating) navigate(`/species/${savedId}`); else { const result = await getSpecies(savedId); setSpecies(result.species); setPayload(result.species.payload); setRevisions(result.revisions); setMessage('Los cambios quedaron guardados en una revisión nueva.'); } } catch (error) { setMessage(error instanceof Error && error.message.includes('revision_conflict') ? 'Otra persona modificó esta especie. Recargá la página y compará los cambios antes de volver a guardar.' : error instanceof Error ? error.message : 'No se pudo guardar.'); } finally { setSaving(false); } }
  async function lifecycleAction() { if (!species || !confirm) return; await speciesAction(confirm === 'retire' ? 'retire_species' : 'restore_species', species.id, species.revision, reason); setConfirm(null); const result = await getSpecies(species.id); setSpecies(result.species); setRevisions(result.revisions); }
  async function validate() { if (!species) return; await speciesAction('validate_revision', species.id, species.revision); const result = await getSpecies(species.id); setSpecies(result.species); setRevisions(result.revisions); }
  if (loading) return <Loading label="Abriendo ficha editorial…" />; if (!creating && !species) return <Empty title="Especie no encontrada" detail={message || 'El registro no existe o fue retirado.'} />;
  return <><button className="back-link" onClick={() => navigate('/species')}><ArrowLeft size={17} /> Volver al catálogo</button><PageHeader eyebrow={creating ? 'ALTA DE ESPECIE' : `REVISIÓN ${species?.revision}`} title={title} subtitle={payload.scientificName || 'Completá la identidad taxonómica'} action={<div className="header-actions">{species && <button className="secondary" onClick={() => setConfirm(species.lifecycle === 'active' ? 'retire' : 'restore')}>{species.lifecycle === 'active' ? <Trash2 size={17} /> : <ArchiveRestore size={17} />}{species.lifecycle === 'active' ? 'Dar de baja' : 'Restaurar'}</button>}<button className="primary" disabled={!dirty || saving} onClick={() => void save()}><Save size={17} />{saving ? 'Guardando…' : 'Guardar revisión'}</button></div>} />
    {message && <Notice kind={message.startsWith('Los cambios') ? 'success' : 'error'}>{message}</Notice>}
    <section className="editor-layout"><aside className="editor-tabs">{tabs.map(([key, label]) => <button className={tab === key ? 'active' : ''} onClick={() => setTab(key)} key={key}>{key === 'history' && <History size={17} />}{label}</button>)}<div className="editor-state"><small>Estado editorial</small><span className={`status ${species?.validationState ?? 'unreviewed'}`}>{species?.validationState === 'validated' ? 'Validada' : species?.validationState === 'needs_review' ? 'Revisar' : 'Sin revisar'}</span>{species && species.validationState !== 'validated' && <button className="secondary wide" onClick={() => void validate()}><ShieldCheck size={17} /> Validar revisión</button>}</div></aside><article className="panel editor-panel">
      {tab === 'identity' && <FormSection title="Identidad" detail="Nombres estables que permiten reconocer la especie en todo el sistema."><div className="form-grid"><Field label="Código Natura UY" value={catalogCode} onChange={setCatalogCode} required /><Field label="Nombre científico" value={payload.scientificName} onChange={(value) => patch('scientificName', value)} required italic /><Field label="Nombre aceptado" value={payload.acceptedName} onChange={(value) => patch('acceptedName', value)} italic /><Field label="Nombres comunes" value={payload.commonNames.join(', ')} onChange={(value) => patch('commonNames', value.split(',').map((item) => item.trim()).filter(Boolean))} hint="Separados por comas" /></div></FormSection>}
      {tab === 'taxonomy' && <FormSection title="Clasificación taxonómica" detail="La aplicación utiliza estas jerarquías para filtros y navegación."><div className="form-grid three">{(['kingdom','phylum','class','order','family','genus'] as const).map((key) => <Field key={key} label={{ kingdom:'Reino',phylum:'Filo',class:'Clase',order:'Orden',family:'Familia',genus:'Género' }[key]} value={payload.taxonomy[key]} onChange={(value) => patch('taxonomy', { ...payload.taxonomy, [key]: value })} italic={key !== 'kingdom'} />)}</div></FormSection>}
      {tab === 'presence' && <FormSection title="Presencia en Uruguay" detail="Origen, establecimiento, estacionalidad y certeza son dimensiones diferentes."><div className="form-grid two"><SelectField label="Origen" value={payload.origin} onChange={(value) => patch('origin', value as SpeciesPayload['origin'])} options={[['native','Nativa'],['introduced','Introducida'],['unknown','Desconocido']]} /><SelectField label="Establecimiento" value={payload.establishment} onChange={(value) => patch('establishment', value as SpeciesPayload['establishment'])} options={[['established','Establecida'],['casual','Casual'],['uncertain','Incierto']]} /><SelectField label="Estacionalidad" value={payload.seasonality} onChange={(value) => patch('seasonality', value as SpeciesPayload['seasonality'])} options={[['resident','Residente'],['migratory','Migratoria'],['occasional','Ocasional'],['unknown','Desconocida']]} /><SelectField label="Certeza de presencia" value={payload.presenceCertainty} onChange={(value) => patch('presenceCertainty', value as SpeciesPayload['presenceCertainty'])} options={[['confirmed','Confirmada'],['probable','Probable'],['uncertain','Incierta']]} /><Field label="Abundancia" value={payload.abundanceStatus} onChange={(value) => patch('abundanceStatus', value)} hint="No confundir con conservación" /></div></FormSection>}
      {tab === 'biology' && <FormSection title="Biología y descripción" detail="Contenido comprensible para el público general."><div className="form-stack"><TextArea label="Descripción" value={payload.description} onChange={(value) => patch('description', value)} /><div className="form-grid two"><Field label="Hábitats" value={payload.habitat.join(', ')} onChange={(value) => patch('habitat', split(value))} hint="Separados por comas" /><Field label="Alimentación" value={payload.diet.join(', ')} onChange={(value) => patch('diet', split(value))} hint="Separada por comas" /><Field label="Tamaño" value={payload.size} onChange={(value) => patch('size', value)} /><Field label="Nota relevante" value={payload.relevantNote} onChange={(value) => patch('relevantNote', value)} /></div></div></FormSection>}
      {tab === 'conservation' && <FormSection title="Estado de conservación" detail="Este estado es independiente de la abundancia observada."><div className="form-grid two"><Field label="Sistema" value={payload.conservation.system} onChange={(value) => patch('conservation', { ...payload.conservation, system: value })} /><SelectField label="Categoría" value={payload.conservation.category} onChange={(value) => patch('conservation', { ...payload.conservation, category: value as SpeciesPayload['conservation']['category'] })} options={['NE','DD','LC','NT','VU','EN','CR','EW','EX'].map((value) => [value, value])} /><Field label="Fuente" value={payload.conservation.source} onChange={(value) => patch('conservation', { ...payload.conservation, source: value })} /><Field type="date" label="Fecha de evaluación" value={payload.conservation.assessedAt} onChange={(value) => patch('conservation', { ...payload.conservation, assessedAt: value })} /></div></FormSection>}
      {tab === 'sources' && <FormSection title="Procedencia por campo" detail="Asociá cada dato con su fuente concreta; por ejemplo taxonomy.order, conservation.status o description."><div className="source-list">{payload.fieldSources.map((source, index) => <article className="source-card" key={`${source.fieldPath}-${index}`}><button className="icon-button source-remove" aria-label="Quitar fuente" onClick={() => patch('fieldSources', payload.fieldSources.filter((_, itemIndex) => itemIndex !== index))}><Trash2 /></button><div className="form-grid"><Field label="Ruta del campo" value={source.fieldPath} onChange={(value) => patch('fieldSources', payload.fieldSources.map((item, itemIndex) => itemIndex === index ? { ...item, fieldPath: value } : item))} hint="Ej.: taxonomy.order" /><Field label="Nombre de la fuente" value={source.name} onChange={(value) => patch('fieldSources', payload.fieldSources.map((item, itemIndex) => itemIndex === index ? { ...item, name: value } : item))} /><Field label="URL" value={source.url} onChange={(value) => patch('fieldSources', payload.fieldSources.map((item, itemIndex) => itemIndex === index ? { ...item, url: value } : item))} /><Field label="Cita" value={source.citation} onChange={(value) => patch('fieldSources', payload.fieldSources.map((item, itemIndex) => itemIndex === index ? { ...item, citation: value } : item))} /><label className="field full"><span>Nota</span><textarea rows={2} value={source.note} onChange={(event) => patch('fieldSources', payload.fieldSources.map((item, itemIndex) => itemIndex === index ? { ...item, note: event.target.value } : item))} /></label></div></article>)}</div><button className="secondary" onClick={() => patch('fieldSources', [...payload.fieldSources, { fieldPath: '', name: '', citation: '', url: '', note: '' }])}><Plus size={17} /> Agregar fuente</button></FormSection>}
      {tab === 'history' && <FormSection title="Historial de revisiones" detail="Las versiones anteriores nunca se eliminan."><div className="timeline">{revisions.map((revision) => <article key={revision.id}><span className="timeline-icon">{revision.validationState === 'validated' ? <Check /> : <Clock3 />}</span><div><header><strong>Revisión {revision.revision}</strong><span className={`status ${revision.validationState}`}>{revision.validationState}</span></header><p>{revision.reason}</p><small>{revision.editedBy} · {new Date(revision.editedAt).toLocaleString('es-UY')}</small>{species && revision.revision !== species.revision && <button className="link-button" onClick={() => void rollbackRevision(species.id, revision.revision, species.revision, `Restauración de revisión ${revision.revision}`)}>Restaurar como revisión nueva</button>}</div></article>)}</div></FormSection>}
      {tab !== 'history' && <label className="field full"><span>Motivo del cambio</span><input value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Ej.: rectificación según fuente oficial" /></label>}
    </article></section>
    {confirm && <Modal title={confirm === 'retire' ? 'Dar de baja la especie' : 'Restaurar la especie'} onClose={() => setConfirm(null)}><p>{confirm === 'retire' ? 'La especie dejará de aparecer en la próxima publicación, pero todo su historial se conservará.' : 'La especie volverá a incluirse en el catálogo publicado.'}</p><label className="field"><span>Motivo obligatorio</span><textarea value={reason} onChange={(event) => setReason(event.target.value)} /></label><footer className="modal-actions"><button className="secondary" onClick={() => setConfirm(null)}>Cancelar</button><button className="primary" disabled={!reason.trim()} onClick={() => void lifecycleAction()}>Confirmar</button></footer></Modal>}
  </>;
}

const split = (value: string) => value.split(',').map((item) => item.trim()).filter(Boolean);
function FormSection({ title, detail, children }: { title: string; detail: string; children: React.ReactNode }) { return <section className="form-section"><header><h2>{title}</h2><p>{detail}</p></header>{children}</section>; }
function Field({ label, value, onChange, required, italic, hint, type = 'text' }: { label: string; value: string; onChange(value: string): void; required?: boolean; italic?: boolean; hint?: string; type?: string }) { return <label className="field"><span>{label}{required && ' *'}</span><input className={italic ? 'italic' : ''} type={type} value={value} onChange={(event) => onChange(event.target.value)} required={required} />{hint && <small>{hint}</small>}</label>; }
function TextArea({ label, value, onChange }: { label: string; value: string; onChange(value: string): void }) { return <label className="field"><span>{label}</span><textarea rows={6} value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
function SelectField({ label, value, onChange, options }: { label: string; value: string; onChange(value: string): void; options: string[][] }) { return <label className="field"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}>{options.map(([key, text]) => <option value={key} key={key}>{text}</option>)}</select></label>; }
