import { ChevronLeft, ChevronRight, Filter, Leaf, Plus, Search } from 'lucide-react';
import { useEffect, useState } from 'react';

import { Empty, Loading, PageHeader } from '../components/Ui';
import type { SpeciesSummary } from '../domain';
import { listSpecies, type SpeciesFilters } from '../lib/api';
import { navigate } from '../lib/router';

export function SpeciesListPage(): React.JSX.Element {
  const initialQuery = new URLSearchParams(window.location.search).get('q') ?? '';
  const [filters, setFilters] = useState<SpeciesFilters>({ query: initialQuery, page: 0, pageSize: 25 });
  const [result, setResult] = useState<{ rows: SpeciesSummary[]; count: number } | null>(null); const [error, setError] = useState('');
  useEffect(() => { const timeout = window.setTimeout(() => { void listSpecies(filters).then(setResult).catch((reason: Error) => setError(reason.message)); }, 180); return () => clearTimeout(timeout); }, [filters]);
  const pages = Math.max(1, Math.ceil((result?.count ?? 0) / (filters.pageSize ?? 25)));
  return <><PageHeader eyebrow="CATÁLOGO" title="Especies" subtitle="Buscá, filtrá y rectificá la información publicada." action={<button className="primary" onClick={() => navigate('/species/new')}><Plus size={18} /> Nueva especie</button>} />
    <section className="panel table-panel"><div className="filter-bar"><label className="search grow"><Search size={19} /><input value={filters.query ?? ''} onChange={(event) => setFilters({ ...filters, query: event.target.value, page: 0 })} placeholder="Nombre común, científico, familia o código…" /></label><span className="filter-label"><Filter size={17} /> Filtros</span><select value={filters.taxonomicClass ?? ''} onChange={(event) => setFilters({ ...filters, taxonomicClass: event.target.value, page: 0 })}><option value="">Todas las clases</option><option>Aves</option><option>Mammalia</option><option>Reptilia</option><option>Amphibia</option><option>Actinopterygii</option><option>Chondrichthyes</option></select><select value={filters.validationState ?? ''} onChange={(event) => setFilters({ ...filters, validationState: event.target.value, page: 0 })}><option value="">Cualquier revisión</option><option value="unreviewed">Sin revisar</option><option value="needs_review">Necesita revisión</option><option value="validated">Validada</option></select><select value={filters.lifecycle ?? ''} onChange={(event) => setFilters({ ...filters, lifecycle: event.target.value, page: 0 })}><option value="">Activas y retiradas</option><option value="active">Activas</option><option value="retired">Retiradas</option></select><select value={filters.missing ?? ''} onChange={(event) => setFilters({ ...filters, missing: event.target.value as SpeciesFilters['missing'], page: 0 })}><option value="">Cualquier contenido</option><option value="image">Sin imagen</option><option value="audio">Sin audio</option><option value="description">Sin descripción</option></select></div>
      {error ? <Empty title="No pudimos consultar las especies" detail={error} /> : !result ? <Loading /> : result.rows.length === 0 ? <Empty title="Sin resultados" detail="Probá con otros términos o quitá algún filtro." /> : <><div className="data-table"><div className="table-row table-head"><span>Especie</span><span>Clasificación</span><span>Código</span><span>Revisión</span><span></span></div>{result.rows.map((item) => <button className="table-row" key={item.id} onClick={() => navigate(`/species/${item.id}`)}><span className="species-cell"><span className={item.imageUrl ? 'species-thumb ready' : 'species-thumb'}>{item.imageUrl ? <img src={item.imageUrl} alt="" /> : <Leaf />}</span><span className="species-name"><strong>{item.payload.commonNames[0] ?? item.payload.scientificName}</strong><em>{item.payload.scientificName}</em></span></span><span><b>{item.payload.taxonomy.class}</b><small>{item.payload.taxonomy.order} · {item.payload.taxonomy.family}</small></span><code>{item.catalogCode}</code><span className={`status ${item.validationState}`}>{item.validationState === 'validated' ? 'Validada' : item.validationState === 'needs_review' ? 'Revisar' : 'Sin revisar'}</span><ChevronRight /></button>)}</div><footer className="pagination"><span>{result.count.toLocaleString('es-UY')} resultados</span><div><button className="icon-button" disabled={!filters.page} onClick={() => setFilters({ ...filters, page: (filters.page ?? 0) - 1 })}><ChevronLeft /></button><span>Página {(filters.page ?? 0) + 1} de {pages}</span><button className="icon-button" disabled={(filters.page ?? 0) + 1 >= pages} onClick={() => setFilters({ ...filters, page: (filters.page ?? 0) + 1 })}><ChevronRight /></button></div></footer></>}
    </section></>;
}
