import { useEffect, useRef, useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AnimatePresence, MotiView } from 'moti';

import type { Species } from '../src/domain/entities/species';
import { speciesRepository } from '../src/data/repositories/speciesRepository';
import { BackIcon, CheckIcon, ChevronRightIcon, TaxonomyIcon } from '../src/presentation/components/TabIcons';
import { SpeciesImage } from '../src/presentation/components/SpeciesImage';
import { PhotoLightbox } from '../src/presentation/components/PhotoLightbox';
import { haptics } from '../src/presentation/haptics';
import { useTheme } from '../src/presentation/theme/ThemeProvider';

type Quiz = { question: string; options: string[]; correctIndex: number; success: string; retry: string };
type Visual = 'map' | 'tree' | 'animalia' | 'chordata' | 'aves' | 'order' | 'family' | 'name' | 'evidence' | 'population' | 'type';
type Lesson = { eyebrow: string; title: string; body: string; fact: string; visual: Visual; quiz?: Quiz };

const LESSONS: Lesson[] = [
  { eyebrow: 'EMPECEMOS', title: 'Un mapa para entender la vida', body: 'La taxonomía es la ciencia que identifica, describe, nombra y clasifica a los seres vivos. Nos da un idioma común para conectar observaciones, colecciones y conocimiento, aunque los nombres cotidianos cambien de un lugar a otro.', fact: 'Clasificar no es ordenar por gusto: cada grupo propone una relación que puede revisarse con nueva evidencia.', visual: 'map' },
  { eyebrow: 'LA FORMA DEL MAPA', title: 'Grupos dentro de grupos', body: 'La clasificación va de conjuntos amplios a otros cada vez más precisos. El ñandú y el tero pertenecen a Aves; el carpincho, a Mammalia; y el yacaré, a Reptilia. Todos conservan las ramas mayores Animalia y Chordata.', fact: 'Pensala como un árbol con ramas, nunca como una escalera de organismos “inferiores” y “superiores”.', visual: 'tree' },
  { eyebrow: 'PASO 1 · REINO', title: 'Animalia: el punto de partida', body: 'Un reino reúne una enorme diversidad. Los animales son pluricelulares, obtienen energía consumiendo materia orgánica y sus células no tienen pared celular. Natura UY empieza aquí porque su catálogo actual está dedicado a animales.', fact: 'Animalia es apenas una gran rama: incluye muchos filos con planes corporales profundamente distintos.', visual: 'animalia' },
  { eyebrow: 'PASO 2 · FILO', title: 'Chordata: un rasgo compartido', body: 'Un filo reúne grandes linajes con una organización corporal común. Los cordados presentan una notocorda en alguna etapa del desarrollo. Aquí están los vertebrados del catálogo: peces, anfibios, reptiles, aves y mamíferos.', fact: 'No todos los cordados conservan una columna vertebral, pero comparten ese origen estructural durante su desarrollo.', visual: 'chordata' },
  { eyebrow: 'PASO 3 · CLASE', title: 'Las clases abren grandes ramas', body: 'Una clase agrupa órdenes emparentados. Aves, Mammalia y Reptilia son clases. Las aves son vertebrados endotermos con plumas, pico y huevos con cáscara; volar es frecuente, pero no define al grupo.', fact: 'Las clasificaciones modernas buscan reflejar parentesco evolutivo, no solamente parecido exterior.', visual: 'aves', quiz: { question: '¿Qué rasgo distingue a todas las aves actuales?', options: ['Las plumas', 'El vuelo', 'Vivir en árboles'], correctIndex: 0, success: 'Exacto: incluso las aves que no vuelan tienen plumas.', retry: 'No todas vuelan ni viven en árboles. La clave son las plumas.' } },
  { eyebrow: 'PASO 4 · ORDEN', title: 'El árbol vuelve a ramificarse', body: 'Dentro de una clase, cada orden reúne familias con un antepasado común relativamente cercano. Para reconocerlos se combinan anatomía, conducta, ecología y ADN: un único rasgo visible rara vez alcanza.', fact: 'En aves, muchos nombres de órdenes terminan en “-iformes”. Es una pista de nomenclatura, no una definición biológica.', visual: 'order' },
  { eyebrow: 'PASO 5 · FAMILIA', title: 'Parientes todavía más cercanos', body: 'Una familia reúne géneros con una historia evolutiva más reciente. Sus integrantes suelen conservar combinaciones comparables de forma, alimentación o comportamiento, aunque pueden ocupar ambientes diferentes.', fact: 'En zoología, muchos nombres de familia terminan en “-idae”, como Furnariidae.', visual: 'family', quiz: { question: 'Si dos especies comparten familia, ¿qué comparten necesariamente?', options: ['También orden, clase, filo y reino', 'Exactamente el mismo aspecto', 'El mismo género'], correctIndex: 0, success: '¡Sí! Cada categoría pequeña está contenida en todas las mayores.', retry: 'No obliga a compartir género ni aspecto, pero sí las categorías superiores.' } },
  { eyebrow: 'PASOS 6 Y 7', title: 'Género y especie forman el nombre', body: 'La nomenclatura binomial usa dos palabras: primero el género, con inicial mayúscula, y luego el epíteto específico, en minúscula. Ambas se escriben en cursiva: Hydrochoerus hydrochaeris. Juntas forman el nombre de la especie; el epíteto solo no alcanza.', fact: 'Luego de escribirlo completo, el género puede abreviarse —H. hydrochaeris— sólo si no genera ambigüedad.', visual: 'name', quiz: { question: '¿Cuál está escrito correctamente?', options: ['Hydrochoerus hydrochaeris', 'hydrochoerus Hydrochaeris', 'hydrochaeris'], correctIndex: 0, success: 'Correcto: género con mayúscula, epíteto con minúscula y ambos en cursiva.', retry: 'Buscá dos palabras: género con mayúscula y epíteto con minúscula.' } },
  { eyebrow: 'UNA DISTINCIÓN ÚTIL', title: 'Especie no significa individuo', body: 'Una especie reúne poblaciones conectadas por una historia evolutiva. Una población es el conjunto de individuos que vive en un lugar y tiempo determinados. Observar pocos ejemplares en un sitio no prueba que toda la especie sea rara.', fact: 'Abundancia, distribución, conservación y facilidad de observación responden preguntas distintas.', visual: 'population' },
  { eyebrow: 'CIENCIA EN MOVIMIENTO', title: '¿Por qué cambian los nombres?', body: 'La clasificación es una hipótesis científica. Se contrasta con anatomía, fósiles, desarrollo, distribución, conducta y ADN. Si nueva evidencia muestra otra relación, una especie puede cambiar de género o un grupo puede dividirse.', fact: 'Los nombres anteriores quedan como sinónimos para conectar publicaciones y registros históricos.', visual: 'evidence', quiz: { question: 'Dos animales se parecen mucho. ¿Qué podemos concluir?', options: ['Hace falta combinar más evidencias', 'Siempre son del mismo orden', 'Uno desciende del otro'], correctIndex: 0, success: 'Exacto: el parecido es una pista, no una sentencia.', retry: 'La convergencia puede producir parecidos sin parentesco cercano.' } },
  { eyebrow: 'LA REFERENCIA MATERIAL', title: 'Un ejemplar fija el nombre', body: 'Cuando se describe una especie se designa un ejemplar tipo y se deposita en una colección científica. No tiene que ser el más típico ni el más lindo: es la referencia objetiva que vincula el nombre con un organismo.', fact: 'Las colecciones biológicas son bibliotecas de evidencia y permiten revisar identificaciones muchos años después.', visual: 'type', quiz: { question: '¿Qué categoría es más específica?', options: ['Género', 'Clase', 'Filo'], correctIndex: 0, success: '¡Muy bien! Género está más cerca de especie.', retry: 'El recorrido se afina: filo → clase → orden → familia → género → especie.' } },
];

const PATH = ['Animalia', 'Chordata', 'Aves', 'Passeriformes', 'Furnariidae', 'Asthenes', 'A. pyrrholeuca'];
const RANKS = ['Reino', 'Filo', 'Clase', 'Orden', 'Familia', 'Género', 'Especie'];
const BRANCH_CODES = ['R_american', 'V_chilensi', 'H_hydrocha', 'C_latirost'];

function MiniQuiz({ quiz, answer, choose }: { quiz: Quiz; answer: number | null; choose: (value: number) => void }): React.JSX.Element {
  const { colors, radius, typography } = useTheme();
  return <View style={styles.quizBlock}><Text style={[typography.title, { color: colors.text }]}>{quiz.question}</Text><View style={styles.answers}>{quiz.options.map((option, index) => { const correct = answer !== null && index === quiz.correctIndex; const wrong = answer === index && !correct; return <Pressable key={option} disabled={answer !== null} onPress={() => choose(index)} style={[styles.answer, { borderRadius: radius.lg, borderColor: correct ? colors.success : wrong ? colors.danger : colors.border, backgroundColor: correct ? colors.primaryContainer : colors.surface }]}><View style={[styles.answerLetter, { backgroundColor: correct ? colors.success : wrong ? colors.danger : colors.surfaceVariant, borderRadius: radius.pill }]}>{correct ? <CheckIcon color="#FFF" size={17} /> : <Text style={[typography.label, { color: wrong ? '#FFF' : colors.text }]}>{String.fromCharCode(65 + index)}</Text>}</View><Text style={[typography.body, styles.flex, { color: colors.text }]}>{option}</Text></Pressable>; })}</View>{answer !== null && <MotiView from={{ opacity: 0, translateY: 5 }} animate={{ opacity: 1, translateY: 0 }}><Text style={[typography.body, { color: answer === quiz.correctIndex ? colors.success : colors.danger }]}>{answer === quiz.correctIndex ? quiz.success : quiz.retry}</Text></MotiView>}</View>;
}

function BranchTree({ species, onPhoto }: { species: Species[]; onPhoto: (item: Species) => void }): React.JSX.Element {
  const { colors, radius, typography } = useTheme();
  const groups = [{ label: 'Aves', items: species.filter((x) => x.taxonomy.clase === 'Aves'), color: '#D8E7D3' }, { label: 'Mammalia', items: species.filter((x) => x.taxonomy.clase === 'Mammalia'), color: '#EADCB8' }, { label: 'Reptilia', items: species.filter((x) => x.taxonomy.clase === 'Reptilia'), color: '#D9E6DE' }];
  return <View style={[styles.treeStage, { backgroundColor: '#F3E8CB', borderRadius: radius.xl }]}><MotiView from={{ opacity: 0, translateY: -8 }} animate={{ opacity: 1, translateY: 0 }} style={[styles.treeRoot, { backgroundColor: colors.primary, borderRadius: radius.pill }]}><Text style={[typography.label, { color: colors.onPrimary }]}>Animalia › Chordata</Text></MotiView><MotiView from={{ height: 0 }} animate={{ height: 22 }} style={[styles.trunk, { backgroundColor: colors.primary }]} /><MotiView from={{ width: '5%' }} animate={{ width: '70%' }} transition={{ type: 'timing', duration: 450 }} style={[styles.branchLine, { backgroundColor: colors.primary }]} /><View style={styles.treeGroups}>{groups.map((group, i) => <MotiView key={group.label} from={{ opacity: 0, translateY: 12 }} animate={{ opacity: 1, translateY: 0 }} transition={{ type: 'spring', delay: 180 + i * 100 }} style={styles.treeColumn}><View style={[styles.classNode, { backgroundColor: group.color, borderRadius: radius.md }]}><Text style={[typography.caption, { color: colors.text }]}>{group.label}</Text></View>{group.items.map((item) => <Pressable key={item.codigo} onPress={() => onPhoto(item)} style={styles.miniSpecies}><SpeciesImage species={item} height={48} style={styles.miniImage} borderRadius={24} bordered={false} glyphSize={22} transition={0} /><Text numberOfLines={2} style={[typography.caption, { color: colors.text, textAlign: 'center' }]}>{item.displayName}</Text></Pressable>)}</MotiView>)}</View></View>;
}

function LessonVisual({ type, species, onPhoto }: { type: Visual; species: Species[]; onPhoto: (item: Species) => void }): React.JSX.Element {
  const { colors, radius, typography } = useTheme();
  if (type === 'tree') return <BranchTree species={species} onPhoto={onPhoto} />;
  if (type === 'chordata' || type === 'aves') return <View style={[styles.imageStage, { backgroundColor: type === 'aves' ? '#F1D6D2' : '#E9E3C9', borderRadius: radius.xl }]}><Image source={type === 'aves' ? require('../assets/images/taxonomy/aves.png') : require('../assets/images/taxonomy/chordata-vertebrates.png')} resizeMode="contain" style={styles.heroImage} accessibilityLabel="Diversidad de vertebrados de Uruguay" /><View style={[styles.visualLabel, { backgroundColor: 'rgba(255,255,255,.88)', borderRadius: radius.pill }]}><Text style={[typography.label, { color: colors.text }]}>{type === 'aves' ? 'Animalia › Chordata › Aves' : 'Animalia › Chordata'}</Text></View></View>;
  if (type === 'name') return <View style={[styles.nameStage, { backgroundColor: '#E4EFE5', borderRadius: radius.xl }]}><Text style={[typography.eyebrow, { color: colors.primary }]}>NOMENCLATURA BINOMIAL</Text><Text style={[typography.display, styles.italic, { color: colors.text }]}>Hydrochoerus hydrochaeris</Text><View style={styles.nameParts}><Text style={[typography.caption, { color: colors.primary }]}>Género: mayúscula ↑</Text><Text style={[typography.caption, { color: colors.primary }]}>↑ epíteto: minúscula</Text></View><Text style={[typography.caption, { color: colors.textSecondary }]}>Las dos palabras van en cursiva.</Text></View>;
  if (type === 'population') return <View style={[styles.populationStage, { backgroundColor: '#DCE8D6', borderRadius: radius.xl }]}>{Array.from({ length: 7 }, (_, i) => <MotiView key={i} from={{ opacity: 0, scale: .3 }} animate={{ opacity: 1, scale: 1 }} transition={{ type: 'spring', delay: i * 65 }} style={[styles.individual, { left: `${12 + (i % 4) * 22}%`, top: 48 + Math.floor(i / 4) * 58, backgroundColor: i > 4 ? '#8A641B' : colors.primary }]}><Text style={{ color: '#FFF' }}>●</Text></MotiView>)}<Text style={[typography.label, styles.populationLabel, { color: colors.text }]}>individuos → población → especie</Text></View>;
  if (type === 'type') return <View style={[styles.nameStage, { backgroundColor: '#EADFC6', borderRadius: radius.xl }]}><View style={[styles.collectionCard, { backgroundColor: colors.surface, borderRadius: radius.lg }]}><Text style={styles.specimen}>◈</Text><View><Text style={[typography.eyebrow, { color: '#765819' }]}>COLECCIÓN CIENTÍFICA</Text><Text style={[typography.title, { color: colors.text }]}>Ejemplar tipo</Text><Text style={[typography.caption, { color: colors.textSecondary }]}>nombre ↔ evidencia material</Text></View></View></View>;
  if (type === 'evidence') return <View style={[styles.evidence, { backgroundColor: '#EDE5F3', borderRadius: radius.xl }]}>{['Anatomía', 'ADN', 'Fósiles', 'Conducta', 'Distribución'].map((label, i) => <MotiView key={label} from={{ opacity: 0, scale: .8 }} animate={{ opacity: 1, scale: 1 }} transition={{ type: 'timing', delay: i * 60 }} style={[styles.evidenceNode, { backgroundColor: i === 1 ? '#725486' : '#FFF', borderRadius: radius.pill }]}><Text style={[typography.label, { color: i === 1 ? '#FFF' : colors.text }]}>{label}</Text></MotiView>)}<View style={[styles.evidenceResult, { backgroundColor: '#725486', borderRadius: radius.lg }]}><TaxonomyIcon color="#FFF" size={25} /><Text style={[typography.label, { color: '#FFF' }]}>Hipótesis de parentesco</Text></View></View>;
  const active = type === 'animalia' ? 0 : type === 'order' ? 3 : type === 'family' ? 4 : -1;
  const path = type === 'map' ? PATH.slice(0, 3) : active >= 0 ? PATH.slice(0, active + 1) : PATH;
  return <View style={[styles.pathStage, { backgroundColor: '#F4E9C9', borderRadius: radius.xl }]}>{path.map((value, i) => <MotiView key={value} from={{ opacity: 0, translateX: -15 }} animate={{ opacity: 1, translateX: 0 }} transition={{ type: 'timing', delay: i * 55 }} style={[styles.pathRow, { width: `${100 - i * 5}%`, backgroundColor: i === path.length - 1 ? '#8A641B' : 'rgba(255,255,255,.74)', borderRadius: radius.md }]}><Text style={[typography.eyebrow, { color: i === path.length - 1 ? '#F7EAC8' : colors.textMuted }]}>{RANKS[i]}</Text><Text style={[typography.label, { color: i === path.length - 1 ? '#FFF' : colors.text }]}>{value}</Text></MotiView>)}</View>;
}

export default function LearnScreen(): React.JSX.Element {
  const db = useSQLiteContext(); const router = useRouter(); const insets = useSafeAreaInsets(); const { colors, elevation, radius, spacing, typography } = useTheme();
  const scrollRef = useRef<ScrollView>(null); const [page, setPage] = useState(0); const [direction, setDirection] = useState(1); const [answer, setAnswer] = useState<number | null>(null); const [species, setSpecies] = useState<Species[]>([]); const [zoom, setZoom] = useState<Species | null>(null); const lesson = LESSONS[page]!;
  useEffect(() => { let active = true; void speciesRepository.findManyByCodigo(db, BRANCH_CODES).then((items) => { if (active) setSpecies(items); }); return () => { active = false; }; }, [db]);
  useEffect(() => { scrollRef.current?.scrollTo({ y: 0, animated: false }); setAnswer(null); }, [page]);
  const move = (next: number): void => { const bounded = Math.max(0, Math.min(LESSONS.length - 1, next)); setDirection(bounded >= page ? 1 : -1); haptics.tick(); setPage(bounded); };
  const choose = (value: number): void => { setAnswer(value); if (value === lesson.quiz?.correctIndex) haptics.success(); else haptics.error(); };
  return <View style={[styles.screen, { backgroundColor: colors.background, paddingTop: insets.top }]}><View style={[styles.header, { paddingHorizontal: spacing.lg, paddingVertical: spacing.sm }]}><Pressable onPress={() => router.back()} accessibilityLabel="Cerrar guía" style={[styles.back, { backgroundColor: colors.surface, borderRadius: radius.pill }]}><BackIcon color={colors.text} /></Pressable><View style={styles.flex}><Text style={[typography.eyebrow, { color: colors.primary }]}>APRENDER · TAXONOMÍA</Text><Text style={[typography.caption, { color: colors.textMuted }]}>{page + 1} de {LESSONS.length}</Text></View></View><View style={[styles.progressTrack, { backgroundColor: colors.border }]}><MotiView animate={{ width: `${((page + 1) / LESSONS.length) * 100}%` }} transition={{ type: 'timing', duration: 280 }} style={[styles.progress, { backgroundColor: colors.primary }]} /></View>
    <AnimatePresence exitBeforeEnter><MotiView key={page} from={{ opacity: 0, translateX: direction * 34 }} animate={{ opacity: 1, translateX: 0 }} exit={{ opacity: 0, translateX: direction * -24 }} transition={{ type: 'timing', duration: 260 }} style={styles.flex}><ScrollView ref={scrollRef} showsVerticalScrollIndicator={false} contentContainerStyle={{ padding: spacing.lg, paddingBottom: spacing.xl }}><View style={styles.lesson}><LessonVisual type={lesson.visual} species={species} onPhoto={setZoom} /><View><Text style={[typography.eyebrow, { color: colors.primary }]}>{lesson.eyebrow}</Text><Text style={[typography.display, { color: colors.text, marginTop: 7 }]}>{lesson.title}</Text><Text style={[typography.body, { color: colors.textSecondary, marginTop: 12 }]}>{lesson.body}</Text></View>{lesson.quiz && <MiniQuiz quiz={lesson.quiz} answer={answer} choose={choose} />}<View style={[styles.fact, elevation.low, { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.lg }]}><View style={[styles.factIcon, { backgroundColor: '#E7D7AE', borderRadius: radius.pill }]}><Text style={styles.bulb}>✦</Text></View><View style={styles.flex}><Text style={[typography.eyebrow, { color: '#765819' }]}>DATO PARA RECORDAR</Text><Text style={[typography.body, { color: colors.text, marginTop: 4 }]}>{lesson.fact}</Text></View></View></View></ScrollView></MotiView></AnimatePresence>
    <View style={[styles.footer, { paddingHorizontal: spacing.lg, paddingTop: spacing.md, paddingBottom: insets.bottom + spacing.md, backgroundColor: colors.background, borderColor: colors.border }]}><Pressable disabled={page === 0} onPress={() => move(page - 1)} style={[styles.previous, { borderColor: colors.border, borderRadius: radius.pill, opacity: page === 0 ? .35 : 1 }]}><BackIcon color={colors.text} size={18} /><Text style={[typography.label, { color: colors.text }]}>Anterior</Text></Pressable><View style={styles.dots}>{LESSONS.map((_, i) => <View key={i} style={[styles.dot, { width: i === page ? 14 : 5, backgroundColor: i === page ? colors.primary : colors.border, borderRadius: radius.pill }]} />)}</View><Pressable onPress={() => page === LESSONS.length - 1 ? router.push('/taxonomy') : move(page + 1)} style={[styles.next, { backgroundColor: colors.primary, borderRadius: radius.pill }]}><Text style={[typography.label, { color: colors.onPrimary }]}>{page === LESSONS.length - 1 ? 'Explorar' : 'Siguiente'}</Text><ChevronRightIcon color={colors.onPrimary} size={18} /></Pressable></View><PhotoLightbox visible={zoom !== null} uri={zoom?.photo?.fullUrl} label={zoom?.displayName ?? ''} onClose={() => setZoom(null)} /></View>;
}

const styles = StyleSheet.create({
  screen: { flex: 1 }, flex: { flex: 1 }, header: { flexDirection: 'row', alignItems: 'center', gap: 12 }, back: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, progressTrack: { height: 3 }, progress: { height: 3 }, lesson: { gap: 24 },
  imageStage: { height: 235, alignItems: 'center', justifyContent: 'center', overflow: 'hidden', padding: 14 }, heroImage: { width: '100%', height: '100%' }, visualLabel: { position: 'absolute', bottom: 12, paddingHorizontal: 12, paddingVertical: 7 }, pathStage: { minHeight: 235, padding: 16, justifyContent: 'center', gap: 7 }, pathRow: { minHeight: 40, paddingHorizontal: 12, paddingVertical: 7, alignSelf: 'center', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  treeStage: { minHeight: 292, padding: 14, alignItems: 'center' }, treeRoot: { paddingHorizontal: 16, paddingVertical: 8 }, trunk: { width: 2 }, branchLine: { height: 2 }, treeGroups: { width: '100%', flexDirection: 'row', justifyContent: 'space-between' }, treeColumn: { flex: 1, alignItems: 'center', paddingHorizontal: 3 }, classNode: { width: '100%', minHeight: 36, alignItems: 'center', justifyContent: 'center' }, miniSpecies: { marginTop: 9, alignItems: 'center', width: '100%', gap: 4 }, miniImage: { width: 48 },
  nameStage: { minHeight: 235, alignItems: 'center', justifyContent: 'center', padding: 20, gap: 15 }, nameParts: { width: '100%', flexDirection: 'row', justifyContent: 'space-around' }, italic: { fontStyle: 'italic', textAlign: 'center' }, evidence: { minHeight: 235, padding: 18, flexDirection: 'row', flexWrap: 'wrap', alignContent: 'center', justifyContent: 'center', gap: 9 }, evidenceNode: { paddingHorizontal: 15, paddingVertical: 10 }, evidenceResult: { width: '100%', marginTop: 9, padding: 14, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 9 },
  populationStage: { minHeight: 235, alignItems: 'center', position: 'relative' }, individual: { position: 'absolute', width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' }, populationLabel: { position: 'absolute', bottom: 20 }, collectionCard: { padding: 20, flexDirection: 'row', gap: 15, alignItems: 'center' }, specimen: { fontSize: 48, color: '#765819' },
  quizBlock: { gap: 12 }, answers: { gap: 9 }, answer: { minHeight: 58, padding: 12, borderWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 11 }, answerLetter: { width: 30, height: 30, alignItems: 'center', justifyContent: 'center' }, fact: { padding: 15, borderWidth: StyleSheet.hairlineWidth, flexDirection: 'row', alignItems: 'flex-start', gap: 12 }, factIcon: { width: 34, height: 34, alignItems: 'center', justifyContent: 'center' }, bulb: { color: '#765819', fontSize: 20 },
  footer: { borderTopWidth: StyleSheet.hairlineWidth, flexDirection: 'row', alignItems: 'center', gap: 8 }, previous: { minHeight: 46, paddingHorizontal: 12, borderWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 5 }, next: { minHeight: 46, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 4 }, dots: { flex: 1, flexDirection: 'row', justifyContent: 'center', gap: 3 }, dot: { height: 5 },
});
