import { createHash } from 'node:crypto';
import { gzipSync } from 'node:zlib';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { DatabaseSync } from 'node:sqlite';

import { adminClient, chunks, required } from './shared';

type Row = Record<string, unknown>;
const client = adminClient(); const output = resolve(import.meta.dirname, '../dist/catalog'); const databasePath = resolve(output, 'natura.db');
rmSync(output, { recursive: true, force: true }); mkdirSync(output, { recursive: true });

async function fetchAll(table: string, select = '*'): Promise<Row[]> {
  const result: Row[] = []; for (let from = 0; ; from += 1000) { const { data, error } = await client.from(table).select(select).range(from, from + 999); if (error) throw error; result.push(...(data as unknown as Row[])); if (!data || data.length < 1000) return result; }
}

const releaseId = required('CATALOG_RELEASE_ID');
const { data: release, error: releaseError } = await client.from('catalog_releases').update({ status: 'building', started_at: new Date().toISOString(), error: null }).eq('id', releaseId).select('*').single(); if (releaseError) throw releaseError;
const species = (await fetchAll('species')).filter((row) => row.lifecycle === 'active');
const revisions: Row[] = []; for (const batch of chunks(species, 100)) { const ids = batch.map((row) => row.id as string); const { data, error } = await client.from('species_revisions').select('*').in('species_id', ids); if (error) throw error; revisions.push(...(data as Row[]).filter((row) => species.some((item) => item.id === row.species_id && item.current_revision === row.revision))); }
const media = (await fetchAll('media_assets')).filter((row) => row.state === 'ready'); const revisionBySpecies = new Map(revisions.map((row) => [row.species_id as string, row]));
const mediaOrigin = process.env.PUBLIC_MEDIA_ORIGIN ?? 'https://natura-uy-admin.pages.dev';
const items = species.map((record) => { const revision = revisionBySpecies.get(record.id as string); if (!revision) throw new Error(`Missing current revision for ${record.id}`); const payload = revision.payload as Record<string, any>; const assets = media.filter((asset) => asset.species_id === record.id); const image = assets.find((asset) => asset.kind === 'image'); const audio = assets.find((asset) => asset.kind === 'audio'); return { record, revision, payload, image, audio, imageUrl: image ? String(image.external_url ?? `${mediaOrigin}/m/${image.id}/thumb`) : null, fullUrl: image ? String(image.external_url ?? `${mediaOrigin}/m/${image.id}/main`) : null, audioUrl: audio ? String(audio.external_url ?? `${mediaOrigin}/m/${audio.id}/audio`) : null }; });

const scientific = new Set<string>(); const codes = new Set<string>(); const blockers: string[] = []; const warnings: Array<{ code: string; speciesId: string; detail: string }> = [];
for (const item of items) { const name = String(item.payload.scientificName ?? '').trim(); const code = String(item.record.catalog_code); if (!name) blockers.push(`scientific_name_missing:${item.record.id}`); if (scientific.has(name.toLowerCase())) blockers.push(`duplicate_scientific_name:${name}`); scientific.add(name.toLowerCase()); if (codes.has(code)) blockers.push(`duplicate_catalog_code:${code}`); codes.add(code); if (!item.image) warnings.push({ code: 'image_missing', speciesId: String(item.record.id), detail: name }); if (!item.audio) warnings.push({ code: 'audio_missing', speciesId: String(item.record.id), detail: name }); if (!item.payload.description) warnings.push({ code: 'description_missing', speciesId: String(item.record.id), detail: name }); if (item.revision.validation_state !== 'validated') warnings.push({ code: 'not_validated', speciesId: String(item.record.id), detail: name }); }
if (blockers.length) { await client.from('catalog_releases').update({ status: 'failed', error: blockers.join('\n') }).eq('id', releaseId); throw new Error(`Catalog blocked:\n${blockers.join('\n')}`); }

const db = new DatabaseSync(databasePath); db.exec(`pragma journal_mode=delete; pragma foreign_keys=on;
create table species (
 stable_id text not null unique, codigo text primary key, scientific_name text not null, accepted_name text, common_name text not null, common_names text not null,
 kingdom text not null, phylum text not null, clase text not null, orden text not null, familia text not null, genero text not null, epiteto text not null,
 estado_conservacion text not null, conservation_label text not null, conservation_rank integer not null, conservation_system text, conservation_source text, conservation_assessed_at text,
 nativa integer not null, descripcion text not null, alimentacion text not null, tamano text not null,
 image_url text, full_url text, thumb_asset text, audio_url text, image_license text, image_attribution text, image_source text, image_page text,
 accent_light text not null, accent_dark text not null, container_light text not null, on_container_light text not null, container_dark text not null, on_container_dark text not null,
 origin text, establishment text, seasonality text, presence_certainty text, abundance_status text, habitat text not null, diet text not null, relevant_note text, review_status text not null, sources text not null
);
create index idx_species_clase on species(clase); create index idx_species_phylum on species(phylum); create index idx_species_orden on species(orden); create index idx_species_familia on species(familia); create index idx_species_genero on species(genero); create index idx_species_taxonomy_path on species(phylum, clase, orden, familia, genero, common_name collate nocase); create index idx_species_rank on species(conservation_rank); create index idx_species_has_photo on species(image_url); create index idx_species_sort on species(common_name);
create virtual table species_fts using fts5(common_names, scientific_name, familia, genero, content='species', content_rowid='rowid', tokenize="unicode61 remove_diacritics 2");
create table meta (key text primary key, value text not null);`);

const speciesColumnCount = 47;
const insert = db.prepare(`insert into species values (${Array.from({ length: speciesColumnCount }, () => '?').join(',')})`);
const categoryRank: Record<string, number> = { NE: 0, DD: 0, LC: 1, NT: 2, VU: 3, EN: 3, CR: 3, EW: 3, EX: 3 }; const defaults = ['#477052','#BDD0B7','#DCE8D8','#293832','#31533D','#E5F1E2'];
db.exec('begin'); try { for (const item of items) { const p = item.payload; const taxonomy = p.taxonomy ?? {}; const conservation = p.conservation ?? {}; const names: string[] = p.commonNames?.length ? p.commonNames : [p.scientificName]; const palette = item.image?.palette as any; const epithet = String(p.scientificName).split(' ')[1] ?? ''; const category = conservation.category ?? 'NE'; const usesLegacyConservation = category === 'NE' && conservation.legacyStatus; const conservationRaw = usesLegacyConservation ? conservation.legacyStatus : category; const conservationLabel = usesLegacyConservation ? conservation.legacyLabel ?? conservation.legacyStatus : category; const conservationRank = usesLegacyConservation ? Number(conservation.legacyRank ?? 0) : categoryRank[category] ?? 0; const mobileSources = (p.fieldSources ?? []).map((source: Record<string, unknown>) => ({ source: String(source.name ?? ''), record: source.url || source.citation || null, fieldPath: source.fieldPath ?? 'species' })); const values = [String(item.record.id), String(item.record.catalog_code), String(p.scientificName), String(p.acceptedName || p.scientificName), String(names[0] ?? p.scientificName), JSON.stringify(names), taxonomy.kingdom ?? '', taxonomy.phylum ?? '', taxonomy.class ?? '', taxonomy.order ?? '', taxonomy.family ?? '', taxonomy.genus ?? '', epithet, conservationRaw, conservationLabel, conservationRank, conservation.system ?? null, conservation.source ?? null, conservation.assessedAt ?? null, p.origin === 'native' ? 1 : 0, p.description ?? '', (p.diet ?? []).join(', '), p.size ?? '', item.imageUrl, item.fullUrl, null, item.audioUrl, item.image ? String(item.image.original_license ?? item.image.license ?? '') : null, item.image ? String(item.image.author ?? '') : null, item.image ? String(item.image.source_url ?? '') : null, item.image ? String(item.image.source_url ?? '') : null, palette?.accentLight ?? palette?.dominant ?? defaults[0], palette?.accentDark ?? defaults[1], palette?.containerLight ?? defaults[2], palette?.onContainerLight ?? defaults[3], palette?.containerDark ?? defaults[4], palette?.onContainerDark ?? defaults[5], p.origin ?? null, p.establishment ?? null, p.seasonality ?? null, p.presenceCertainty ?? null, p.abundanceStatus ?? null, JSON.stringify(p.habitat ?? []), JSON.stringify(p.diet ?? []), p.relevantNote ?? null, String(item.revision.validation_state), JSON.stringify(mobileSources)]; if (values.length !== speciesColumnCount) throw new Error(`SQLite column mismatch: expected ${speciesColumnCount}, got ${values.length}`); insert.run(...values); }
  db.exec(`insert into species_fts(rowid, common_names, scientific_name, familia, genero) select rowid, replace(replace(replace(common_names, '["', ''), '"]', ''), '","', ' '), scientific_name, familia, genero from species;`); const meta = db.prepare('insert into meta values (?,?)'); meta.run('schema_version', String(release.schema_version)); meta.run('data_version', String(release.data_version)); meta.run('built_at', new Date().toISOString()); meta.run('species_count', String(items.length)); db.exec('commit');
} catch (error) { db.exec('rollback'); db.close(); throw error; }
const integrity = db.prepare('pragma integrity_check').get() as { integrity_check: string }; const count = (db.prepare('select count(*) as n from species').get() as { n: number }).n; if (integrity.integrity_check !== 'ok' || count !== items.length) throw new Error(`SQLite validation failed: ${integrity.integrity_check}, count=${count}`); db.exec('pragma optimize; vacuum;'); db.close();

const publicItems: Array<Record<string, any>> = items.map((item) => ({ id: item.record.id, catalogCode: item.record.catalog_code, ...item.payload, reviewStatus: item.revision.validation_state, media: { image: item.image ? { url: item.imageUrl, fullUrl: item.fullUrl, license: item.image.license, attribution: item.image.author, source: item.image.source_url } : null, audio: item.audioUrl } }));
writeFileSync(resolve(output, 'catalog.json'), JSON.stringify(publicItems, null, 2)); const byClass = new Map<string, unknown[]>(); for (const item of publicItems) { const key = String(item.taxonomy.class || 'unclassified').toLocaleLowerCase(); byClass.set(key, [...(byClass.get(key) ?? []), item]); } for (const [key, records] of byClass) writeFileSync(resolve(output, `${key}.json`), JSON.stringify(records, null, 2));
const database = readFileSync(databasePath); const compressed = gzipSync(database, { level: 9 }); writeFileSync(`${databasePath}.gz`, compressed); const sha256 = createHash('sha256').update(database).digest('hex');
const report = { dataVersion: release.data_version, generatedAt: new Date().toISOString(), speciesCount: items.length, media: { images: items.filter((item) => item.image).length, audio: items.filter((item) => item.audio).length }, blockers, warningCount: warnings.length, warnings }; writeFileSync(resolve(output, 'quality-report.json'), JSON.stringify(report, null, 2));
const manifest = { data_version: release.data_version, schema_version: release.schema_version, published_at: null, database_url: '', compressed_database_url: '', compressed_size: compressed.length, database_size: database.length, sha256, min_app_version: release.min_app_version, quality_report_url: '' }; writeFileSync(resolve(output, 'manifest.json'), JSON.stringify(manifest, null, 2));
writeFileSync(resolve(output, 'build-metadata.json'), JSON.stringify({ releaseId, dataVersion: release.data_version, speciesCount: items.length, databaseSize: database.length, sha256 }, null, 2));
console.log(`Built catalog v${release.data_version}: ${items.length} species, ${(database.length / 1024 / 1024).toFixed(2)} MiB, ${warnings.length} warnings.`);
