/**
 * Stage 04 — bake a tiny local thumbnail for every species that has a photo.
 *
 * These are *not* the images the user ends up looking at. They ship inside the
 * bundle so a card can paint something recognisable on frame one, with zero
 * network, and the full remote photo then cross-fades in over it (expo-image
 * `placeholder`). That keeps the card layout from the prototype while making
 * the list feel instant and usable offline.
 *
 * The thumbnail is deliberately blurred at build time (`.blur()`, below). A
 * sharp 96px image stretched to fill a ~350px-wide card shows raw pixelation
 * during the moment before the real photo lands — reads as a rendering bug,
 * not a placeholder. A soft blur baked into the file removes that ambiguity:
 * it looks like an intentional blur-up (Unsplash/Medium-style), not damage.
 */
import { existsSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import sharp from 'sharp';

import { buildAssetNames, type AssetNameMap } from './lib/assetNames';
import { JsonCache, readJson, writeJson } from './lib/cache';
import { fetchBuffer } from './lib/http';
import { ensureDirs, PATHS } from './lib/paths';
import type { MediaRecord, NormalizedSpecies } from './lib/types';

const SIZE = 160;
const QUALITY = 68;
/** Sigma for sharp's gaussian blur — mild enough to keep colour/shape legible. */
const BLUR_SIGMA = 3;
const CONCURRENCY = 8;

/**
 * Metro resolves `require` statically, so a thumbnail cannot be looked up by a
 * runtime-built path. The map of código -> module is generated here instead,
 * straight from the files that actually exist on disk.
 */
function writeThumbMap(codigos: string[], names: AssetNameMap): void {
  const entries = codigos
    .filter((codigo) => existsSync(resolve(PATHS.thumbs, `${names.get(codigo)!}.webp`)))
    .sort()
    .map((codigo) => `  '${codigo}': require('../../../assets/thumbs/${names.get(codigo)!}.webp'),`)
    .join('\n');

  const file = `/**
 * GENERATED by scripts/04-build-thumbs.ts — do not edit by hand.
 *
 * Bundled, pre-blurred thumbnails, keyed by species código. They paint
 * instantly and work offline, and act as the placeholder the full remote
 * photo fades over.
 */
export const THUMBNAILS: Record<string, number> = {
${entries}
};

export const thumbnailFor = (codigo: string | null | undefined): number | null =>
  codigo ? (THUMBNAILS[codigo] ?? null) : null;
`;

  writeFileSync(resolve(PATHS.root, 'src/data/assets/thumbMap.ts'), file);
  console.log('  wrote src/data/assets/thumbMap.ts');
}

async function buildThumb(assetName: string, url: string): Promise<boolean> {
  const target = resolve(PATHS.thumbs, `${assetName}.webp`);
  if (existsSync(target)) return true;

  const buffer = await fetchBuffer(url);
  if (!buffer) return false;

  try {
    await sharp(buffer)
      .resize(SIZE, SIZE, { fit: 'cover', position: 'attention' })
      .blur(BLUR_SIGMA)
      .webp({ quality: QUALITY })
      .toFile(target);
    return true;
  } catch {
    return false;
  }
}

async function main(): Promise<void> {
  ensureDirs();

  const species = readJson<NormalizedSpecies[]>(resolve(PATHS.out, 'species.json'));
  const media = readJson<Record<string, MediaRecord | null>>(resolve(PATHS.out, 'media.json'));
  const built = new JsonCache<boolean>('thumbs');

  const names = buildAssetNames(species.map((s) => s.codigo));

  const jobs = species
    .map((s) => ({ codigo: s.codigo, url: media[s.codigo]?.imageUrl }))
    .filter((j): j is { codigo: string; url: string } => Boolean(j.url) && !built.get(j.codigo));

  console.log(`04-build-thumbs: ${jobs.length} to render at ${SIZE}px`);

  let done = 0;
  let ok = 0;
  const queue = [...jobs];

  const worker = async (): Promise<void> => {
    for (;;) {
      const job = queue.shift();
      if (!job) return;

      const success = await buildThumb(names.get(job.codigo)!, job.url);
      built.set(job.codigo, success);
      if (success) ok++;

      if (++done % 100 === 0) console.log(`  ${done}/${jobs.length} · ${ok} ok`);
    }
  };

  await Promise.all(Array.from({ length: CONCURRENCY }, worker));
  built.flush();

  const manifest = Object.fromEntries(
    built
      .entries()
      .filter(([, success]) => success)
      .map(([codigo]) => [codigo, names.get(codigo)!]),
  );
  writeJson(resolve(PATHS.out, 'thumbs.json'), manifest);
  writeThumbMap(Object.keys(manifest), names);

  console.log(`  ${Object.keys(manifest).length} thumbnails in assets/thumbs`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
