/** Validate local AVONET/TetrapodTraits extracts and emit reviewable candidates. */
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { PATHS, readJson, slug, writeJson } from './lib';

const INPUT=resolve(PATHS.raw,'traits');
const REDISTRIBUTABLE=new Set(['avonet','tetrapodtraits3','amphibio','fishmorph']);
const REVIEW_ONLY=new Set(['freshwater_fish_shortfalls','mobs','combine','fishbase']);
const CLASSES=new Set(['Aves','Mammalia','Amphibia','Actinopterygii','Chondrichthyes']);
const DIET=new Set(['invertebrates','fish','ectotherm_vertebrates','endotherm_vertebrates','carrion','fruit','nectar','seeds','other_plant_material','algae']);
const HABITAT=new Set(['agroecosistema','costa_playa_dunas','humedal','laguna_estero','mar_abierto','mar_costero','matorral','monte_nativo','pastizal_campo_natural','rio_arroyo','roquedal_sierras','urbano_suburbano']);
const MODES=new Set(['terrestrial','arboreal','aquatic','aerial','fossorial','perching','generalist']);
const ACTIVITY=new Set(['diurnal','nocturnal','both']);const ENVIRONMENTS=new Set(['freshwater','brackish','marine']);const ZONES=new Set(['benthic','demersal','pelagic']);
const SOURCE_CLASSES:Record<string,string[]>={avonet:['Aves'],tetrapodtraits3:['Mammalia','Amphibia'],amphibio:['Amphibia'],fishmorph:['Actinopterygii','Chondrichthyes'],freshwater_fish_shortfalls:['Actinopterygii','Chondrichthyes'],mobs:['Actinopterygii','Chondrichthyes'],combine:['Mammalia'],fishbase:['Actinopterygii','Chondrichthyes']};
const SOURCE_VERSIONS:Record<string,string>={avonet:'AVONET 1.0 / Tobias et al. 2022',tetrapodtraits3:'TetrapodTraits 3 / Zenodo 21815609',amphibio:'AmphiBIO v1 / Figshare 4644424',fishmorph:'FISHMORPH 1.1 / RODARE 1316',freshwater_fish_shortfalls:'Zenodo 19864169',mobs:'MOBS_OPEN snapshot 2026-09-11',combine:'COMBINE 1.0',fishbase:'reference only'};
type Measurement={kind:string;value:number;unit:'mm'|'g';basis:string|null;estimated:boolean};
interface Row {scientificName:string;taxonomicClass:string;recordId:string|null;measurements?:Measurement[];habitat?:string[];diet?:string[];lifeModes?:string[];activity?:string[];aquaticEnvironments?:string[];waterZones?:string[];depthMinM?:number|null;depthMaxM?:number|null;containsImputed?:boolean}
interface Catalog {id:string;scientificName:string;taxonomy?:{class?:string};traits?:unknown;habitat?:string[];diet?:string[]}
interface ResolvedName {scientificName:string;resolution:{acceptedName:string|null}}

function parseCsvLine(line:string,delimiter:string):string[]{const out:string[]=[];let value='';let quoted=false;for(let i=0;i<line.length;i++){const char=line[i]!;if(char==='"'){if(quoted&&line[i+1]==='"'){value+='"';i++;}else quoted=!quoted;}else if(char===delimiter&&!quoted){out.push(value);value='';}else value+=char;}out.push(value);return out;}
function csvRows(file:string):Record<string,string>[] {const lines=readFileSync(file,'utf8').split(/\r?\n/).filter(Boolean);const header=lines.shift()??'';const delimiter=(header.match(/;/g)?.length??0)>(header.match(/,/g)?.length??0)?';':',';const keys=parseCsvLine(header,delimiter);return lines.map((line)=>Object.fromEntries(parseCsvLine(line,delimiter).map((value,index)=>[keys[index]!,value])));}
const positive=(value:string|undefined)=>{const parsed=Number(value);return Number.isFinite(parsed)&&parsed>0?parsed:null;};
const flag=(value:string|undefined)=>Number(value??0)>=0.5;
const unique=(values:string[])=>[...new Set(values)];

function adaptAvonet(names:Set<string>):Row[]{
  const file=resolve(INPUT,'avonet-source/ELEData/TraitData/AVONET1_BirdLife.csv');if(!existsSync(file))return [];
  const lifestyles:Record<string,string>={Aerial:'aerial',Aquatic:'aquatic',Terrestrial:'terrestrial',Insessorial:'perching',Generalist:'generalist'};
  const niches:Record<string,string[]>={Invertivore:['invertebrates'],Piscivore:['fish'],Vertivore:['ectotherm_vertebrates','endotherm_vertebrates'],Scavenger:['carrion'],Frugivore:['fruit'],Nectarivore:['nectar'],Granivore:['seeds'],Herbivore:['other_plant_material'],Omnivore:['invertebrates','fruit','seeds']};
  const habitats:Record<string,string[]>={Forest:['monte_nativo'],Woodland:['monte_nativo'],Shrubland:['matorral'],Grassland:['pastizal_campo_natural'],Wetland:['humedal'],Marine:['mar_abierto'],Rock:['roquedal_sierras'],Coastal:['costa_playa_dunas'],Riverine:['rio_arroyo']};
  return csvRows(file).filter((raw)=>names.has((raw.Species1??'').toLocaleLowerCase())).map((raw)=>{
    const inferred=(raw.Inference??'').toUpperCase()!=='NO';const measurements:Measurement[]=[];
    for(const [column,kind,unit] of [['Mass','body_mass','g'],['Wing.Length','wing_length','mm'],['Tail.Length','tail_length','mm'],['Tarsus.Length','tarsus_length','mm']] as const){const value=positive(raw[column]);if(value)measurements.push({kind,value,unit,basis:null,estimated:inferred});}
    return {scientificName:raw.Species1!,taxonomicClass:'Aves',recordId:raw['Avibase.ID1']||raw.Sequence||null,measurements,habitat:habitats[raw.Habitat!]??[],lifeModes:lifestyles[raw['Primary.Lifestyle']!]? [lifestyles[raw['Primary.Lifestyle']!]!]:[],diet:niches[raw['Trophic.Niche']!]??[],containsImputed:inferred};
  });
}

function adaptTetrapodTraits(names:Set<string>):Row[]{
  const file=resolve(INPUT,'tetrapodtraits3-source.csv');if(!existsSync(file))return [];
  return csvRows(file).filter((raw)=>raw.Class!=='Aves'&&names.has((raw['Scientific.Name']??'').toLocaleLowerCase())).map((raw)=>{
    const measurements:Measurement[]=[];const length=positive(raw.BodyLength_mm);if(length)measurements.push({kind:'body_length',value:length,unit:'mm',basis:raw.LengthMeasure==='SVL'?'SVL':'body_length',estimated:raw.ImputedLength==='1'});const mass=positive(raw.BodyMass_g);if(mass)measurements.push({kind:'body_mass',value:mass,unit:'g',basis:null,estimated:raw.ImputedMass==='1'});
    const lifeModes=unique([flag(raw.Fos)?'fossorial':'',flag(raw.Ter)?'terrestrial':'',flag(raw.Aqu)?'aquatic':'',flag(raw.Arb)?'arboreal':'',flag(raw.Aer)?'aerial':''].filter(Boolean));const diu=flag(raw.Diu),noc=flag(raw.Noc);const activity=diu&&noc?['both']:diu?['diurnal']:noc?['nocturnal']:[];
    const diet=unique([flag(raw.DietInv)?'invertebrates':'',flag(raw.DietVfish)?'fish':'',flag(raw.DietVect)?'ectotherm_vertebrates':'',flag(raw.DietVend)?'endotherm_vertebrates':'',flag(raw.DietScav)?'carrion':'',flag(raw.DietFruit)?'fruit':'',flag(raw.DietNect)?'nectar':'',flag(raw.DietSeed)?'seeds':'',flag(raw.DietPlant)?'other_plant_material':''].filter(Boolean));const aquaticEnvironments=unique([flag(raw.EcoFresh)?'freshwater':'',flag(raw.EcoMar)?'marine':''].filter(Boolean));const habitat=unique([[1,'monte_nativo'],[2,'pastizal_campo_natural'],[3,'matorral'],[4,'pastizal_campo_natural'],[5,'humedal'],[6,'roquedal_sierras'],[9,'mar_costero'],[10,'mar_abierto'],[11,'mar_abierto'],[12,'costa_playa_dunas'],[13,'costa_playa_dunas'],[14,'agroecosistema'],[16,'agroecosistema']].map(([code,value])=>flag(raw[`MajorHabitat_${code}`])?String(value):'').filter(Boolean));
    return {scientificName:raw['Scientific.Name']!,taxonomicClass:raw.Class!,recordId:raw.SourceBodyLength||raw.SourceBodyMass||raw.SourceDiet||null,measurements,habitat,lifeModes,activity,diet,aquaticEnvironments,containsImputed:raw.ImputedLength==='1'||raw.ImputedMass==='1'||raw.ImputedHabitat==='1'||raw.ImputedMajorHabitat==='1'||raw.ImputedEcosystem==='1'||raw.ImputedActTime==='1'};
  });
}

function adaptAmphibio(names:Set<string>):Row[]{
  const file=resolve(INPUT,'amphibio-source/AmphiBIO_v1.csv');if(!existsSync(file))return [];
  return csvRows(file).filter((raw)=>names.has((raw.Species??'').toLocaleLowerCase())).map((raw)=>{const measurements:Measurement[]=[];const length=positive(raw.Body_size_mm);if(length)measurements.push({kind:'body_length',value:length,unit:'mm',basis:raw.Order==='Anura'?'SVL':'TL',estimated:false});const mass=positive(raw.Body_mass_g);if(mass)measurements.push({kind:'body_mass',value:mass,unit:'g',basis:null,estimated:false});const lifeModes=unique([flag(raw.Fos)?'fossorial':'',flag(raw.Ter)?'terrestrial':'',flag(raw.Aqu)?'aquatic':'',flag(raw.Arb)?'arboreal':''].filter(Boolean));const diu=flag(raw.Diu),noc=flag(raw.Noc),crepuscular=flag(raw.Crepu);const activity=crepuscular||(diu&&noc)?['both']:diu?['diurnal']:noc?['nocturnal']:[];const diet=unique([flag(raw.Arthro)?'invertebrates':'',flag(raw.Vert)?'ectotherm_vertebrates':'',flag(raw.Fruits)?'fruit':'',flag(raw.Seeds)?'seeds':'',flag(raw.Leaves)||flag(raw.Flowers)?'other_plant_material':''].filter(Boolean));return {scientificName:raw.Species!,taxonomicClass:'Amphibia',recordId:raw.id||null,measurements,lifeModes,activity,diet,containsImputed:false};});
}

function matchedCatalog(name:string,catalogByName:Map<string,Catalog>,aliases:Map<string,string>):Catalog|undefined{return catalogByName.get(name.toLocaleLowerCase())??catalogByName.get(aliases.get(name.toLocaleLowerCase())?.toLocaleLowerCase()??'');}
function adaptMobs(catalogByName:Map<string,Catalog>,aliases:Map<string,string>):Row[]{
  const file=resolve(INPUT,'mobs-source.csv');if(!existsSync(file))return [];const grouped=new Map<string,{value:number;record:string|null}>();
  for(const raw of csvRows(file)){const name=raw.scientificName??'';const catalogItem=matchedCatalog(name,catalogByName,aliases);if(!catalogItem||!['Actinopterygii','Chondrichthyes'].includes(catalogItem.taxonomy?.class??''))continue;const length=positive(raw.length_cm);if(!length)continue;const current=grouped.get(name);if(!current||length*10>current.value)grouped.set(name,{value:length*10,record:raw.Size_Ref||raw.valid_aphiaID||null});}
  return [...grouped].map(([scientificName,item])=>({scientificName,taxonomicClass:matchedCatalog(scientificName,catalogByName,aliases)?.taxonomy?.class??'Actinopterygii',recordId:item.record,measurements:[{kind:'max_length',value:item.value,unit:'mm',basis:null,estimated:false}],aquaticEnvironments:['marine']}));
}

function adaptFishmorph(catalogByName:Map<string,Catalog>,aliases:Map<string,string>):Row[]{
  const file=resolve(INPUT,'fishmorph-source.csv');if(!existsSync(file))return [];
  return csvRows(file).flatMap((raw)=>{const scientificName=raw['Genus species']??'';const current=matchedCatalog(scientificName,catalogByName,aliases);const lengthCm=positive(raw.MBl);if(!current||!lengthCm)return [];return [{scientificName,taxonomicClass:current.taxonomy?.class??'Actinopterygii',recordId:raw.SpecCode||null,measurements:[{kind:'max_length',value:lengthCm*10,unit:'mm',basis:null,estimated:false}]}];});
}

function validate(row:Row):void{
  if(!/^[A-Z][a-z-]+ [a-z-]+$/.test(row.scientificName)||!CLASSES.has(row.taxonomicClass))throw new Error(`Identidad inválida: ${row.scientificName}`);
  for(const measurement of row.measurements??[])if(!['body_length','body_mass','wing_length','tail_length','tarsus_length','max_length'].includes(measurement.kind)||!Number.isFinite(measurement.value)||measurement.value<=0||!['mm','g'].includes(measurement.unit))throw new Error(`${row.scientificName}: medición inválida`);
  for(const [field,values,allowed] of [['habitat',row.habitat,HABITAT],['diet',row.diet,DIET],['lifeModes',row.lifeModes,MODES],['activity',row.activity,ACTIVITY],['aquaticEnvironments',row.aquaticEnvironments,ENVIRONMENTS],['waterZones',row.waterZones,ZONES]] as const)for(const value of values??[])if(!allowed.has(value))throw new Error(`${row.scientificName}: ${field} inválido: ${value}`);
}

function main():void{
  const catalog=['aves','mammalia','amphibia','actinopterygii','chondrichthyes'].flatMap((file)=>readJson<Catalog[]>(resolve(PATHS.catalog,`${file}.json`)));const byName=new Map(catalog.map((item)=>[item.scientificName.toLocaleLowerCase(),item]));const resolved=readJson<ResolvedName[]>(PATHS.resolved);const aliases=new Map(resolved.filter((item)=>item.resolution.acceptedName&&byName.has(item.resolution.acceptedName.toLocaleLowerCase())&&item.scientificName.toLocaleLowerCase()!==item.resolution.acceptedName.toLocaleLowerCase()).map((item)=>[item.scientificName.toLocaleLowerCase(),item.resolution.acceptedName!]));const names=new Set([...byName.keys(),...aliases.keys()]);const candidates:Record<string,unknown>[]=[];const conflicts:Record<string,unknown>[]=[];
  const inputs:Array<[string,Row[]]>=[['avonet',adaptAvonet(names)],['tetrapodtraits3',adaptTetrapodTraits(names)],['amphibio',adaptAmphibio(names)],['fishmorph',adaptFishmorph(byName,aliases)],['mobs',adaptMobs(byName,aliases)],...(existsSync(INPUT)?readdirSync(INPUT).filter((name)=>name.endsWith('.json')).sort().map((file)=>[file.replace(/\.json$/,''),readJson<Row[]>(resolve(INPUT,file))] as [string,Row[]]):[])];
  for(const [source,rows] of inputs){if(!REDISTRIBUTABLE.has(source)&&!REVIEW_ONLY.has(source))throw new Error(`Fuente sin política de licencia: ${source}`);for(const row of rows){validate(row);const key=row.scientificName.toLocaleLowerCase();const acceptedName=aliases.get(key);const current=byName.get(key)??(acceptedName?byName.get(acceptedName.toLocaleLowerCase()):undefined);if(!current){conflicts.push({source,scientificName:row.scientificName,acceptedName:null,reason:'species_not_in_catalog'});continue;}const synonym=Boolean(acceptedName&&!byName.has(key));if(synonym)conflicts.push({source,scientificName:row.scientificName,acceptedName,reason:'synonym_requires_review'});const estimated=Boolean(row.containsImputed)||(row.measurements??[]).some((item)=>item.estimated);const publishable=REDISTRIBUTABLE.has(source)&&!estimated&&!synonym;const base={speciesId:current.id||slug(current.scientificName),scientificName:current.scientificName,matchedScientificName:row.scientificName,taxonomicMatch:synonym?'synonym':'exact',sourceCode:source,sourceVersion:SOURCE_VERSIONS[source]??'unknown',sourceRecordId:row.recordId,confidence:publishable?1:0.7,decision:publishable?'update':'review'};const traits={measurements:row.measurements??[],lifeModes:row.lifeModes??[],activity:row.activity??[],aquaticEnvironments:row.aquaticEnvironments??[],waterZones:row.waterZones??[],depthMinM:row.depthMinM??null,depthMaxM:row.depthMaxM??null,sources:[source]};const rationale=synonym?`La fuente usa el sinónimo ${row.scientificName}; confirmar la coincidencia con ${current.scientificName}.`:source==='fishbase'?'FishBase es sólo referencia.':estimated?'Contiene valores imputados; requiere aprobación humana.':REVIEW_ONLY.has(source)?'Debe verificarse la licencia del archivo exacto.':'Coincidencia científica exacta y valores observados de fuente redistribuible.';candidates.push({...base,fieldPath:'traits',currentValue:current.traits??null,proposedValue:traits,rationale});if(row.habitat?.length)candidates.push({...base,fieldPath:'habitat',currentValue:current.habitat??[],proposedValue:row.habitat,rationale:synonym?rationale:'El hábitat propuesto puede reemplazar el valor histórico.'});if(row.diet?.length)candidates.push({...base,fieldPath:'diet',currentValue:current.diet??[],proposedValue:row.diet,rationale:synonym?rationale:'Dieta normalizada al vocabulario común.'});}}
  const coverage=Object.fromEntries(inputs.map(([source,rows])=>{const rowKeys=new Set(rows.map((row)=>row.scientificName.toLocaleLowerCase()));const targetClasses=SOURCE_CLASSES[source]??[...CLASSES];const targetNames=new Set(catalog.filter((item)=>targetClasses.includes(item.taxonomy?.class??'')).map((item)=>item.scientificName));return [source,{version:SOURCE_VERSIONS[source]??'unknown',exactMatches:[...rowKeys].filter((key)=>byName.has(key)).length,synonymMatches:[...rowKeys].filter((key)=>aliases.has(key)).length,rows:rows.length,candidates:candidates.filter((item)=>item.sourceCode===source).length,policy:REDISTRIBUTABLE.has(source)?'redistributable':'review_only',byClass:Object.fromEntries([...CLASSES].map((className)=>[className,new Set(rows.filter((row)=>row.taxonomicClass===className).map((row)=>row.scientificName.toLocaleLowerCase())).size]).filter(([,count])=>Number(count)>0)),catalogTargetCount:targetNames.size,unmatchedCatalog:[...targetNames].filter((name)=>!rowKeys.has(name.toLocaleLowerCase()))}];}));const output=resolve(PATHS.reports,'trait-enrichment-candidates.json');writeJson(output,{schemaVersion:1,generatedAt:new Date().toISOString(),targetClasses:[...CLASSES],sourceVersions:SOURCE_VERSIONS,candidateCount:candidates.length,conflictCount:conflicts.length,coverage,candidates,conflicts});console.log(`11-traits: ${candidates.length} candidatos; ${conflicts.length} conflictos; ${output}`);
}
main();
